### ISSUE TITLE
Custom Throughput Throttling samples

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#1086]
We removed built-in throughput throttling options from v6 because we think there is no single way of getting throughput throttling right. We thought about providing some samples on how to add custom throughput throttling (e.g. in message handlers or using behaviors).

See changes here Particular/NServiceBus#3306 realted to Particular/NServiceBus#2859

**Comment by SimonCropp** [comment]
related to https://github.com/Particular/docs.particular.net/pull/1126  ?

**Comment by hmemcpy** [comment]
@SimonCropp yes

**Comment by johnsimons** [comment]
@hmemcpy @timbussmann I have reviewed the current PR, and as far as I can see the "sleep" is done on a behaviour that runs within the timeout of a TransactionScope, so in other words if we are shoing a user how to throttle, I don't think we can do it withing the transaction timeouts.
Looking how MSMQ and other transports that support DTC, I can't figure out how to actually add a sleep using the pipeline because the pipeline tuns inside the receive TransactionScope, so in other words, I don't think we can throtlle in v6 without modifications to the core.

The good news is that it all depends what the user is actually doing, so in the current PR the use case is throttling rest api calls, in this specific scenario the correct way of doing it is to host a separate endpoint that all it does is the rest api calls and then set that to max concurrency of 1 and disable DTC, you then can just do the "sleep" inside the handler code. but as I said it all depends on the use case, so maybe providing a smaple that only caters for a very specific case is not worth it ?

**Comment by timbussmann** [comment]
@johnsimons sorry john, I can't follow you. You reviewed the throttling sample PR? There is no "sleep" for the exact reason you mentioned (and that's not only for dtc cases, transport transactions may have timeouts too, right?). We do deferred redelivery of the message, which seems to be the only really working approach within the pipeline. Otherwhise we would need an extension point outside a transport receive operation.

The sample shows one way of doing it, and it will be another task of documenting the fact, that there may be different approaches (especially the dedicated endpoint for integration), but if users want to do it without a separate endpoint, I currently see no other way than we do it in this sample, therefore I think it's worth it.

**Comment by johnsimons** [comment]
@timbussmann my bad, I see now how u doing it.
But I have a question, because u are in essence delaying the message by doing a send local, wouldn't this then break the `Reply` for the user ?

**Comment by timbussmann** [comment]
@johnsimons very good question. I think it would overwrite the replytoaddress and therefore break reply, but not 100% sure.

**Comment by SimonCropp** [comment]
done http://docs.particular.net/samples/throttling/

**Comment by johnsimons** [comment]
@SimonCropp did u read https://github.com/Particular/docs.particular.net/issues/1086#issuecomment-180033498, in other words, the sample breaks replies.

**Comment by SimonCropp** [comment]
@johnsimons no i didnt. i assumed from this https://github.com/Particular/docs.particular.net/pull/1126#issuecomment-179813846 that it was good to go  

@hmemcpy can u chime in here

**Comment by timbussmann** [comment]
I can try to use the same logic as SLR to keep the replyto header intact. If it works at all, it will certainly make the implementation more complicated.

**Comment by timbussmann** [comment]
fixed replyto here: https://github.com/Particular/docs.particular.net/pull/1181
