### ISSUE TITLE
Cover Circuit Breaker

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1156]
The only place circuit breaker is currently mentioned is Sql Server transport docs (including snippets for configuring it).

Besides explaining how it works and how it can be configured, doco should mention info related to Circuit Breaker that the user can see in the logs (for troubleshooting purposes).

**Comment by weralabaj** [comment]
A nice inspiration http://doc.akka.io/docs/akka/snapshot/common/circuitbreaker.html

**Comment by SimonCropp** [comment]
some other links to either draw content from or link to:

 * https://docs.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker
 * http://docs.masstransit-project.com/en/latest/middleware/circuit_breaker.html
 * https://en.wikipedia.org/wiki/Circuit_breaker_design_pattern
 * http://microservices.io/patterns/reliability/circuit-breaker.html
 * https://martinfowler.com/bliki/CircuitBreaker.html

**Comment by weralabaj** [comment]
Sadly, seems to be still relevant ping @Particular/nservicebus-maintainers

**Comment by andreasohlund** [comment]
Just noting that we're, albeit slowly, moving away from the Circuit Breakers having impact on the users since we as of v7 we no longer shutdown the endpoint when triggering critical error.

With that in mind I wonder if we should just remove the doco, https://docs.particular.net/transports/sql/connection-settings?version=sqltransport_4, since there should no longer be any need for the users to tweak it?

That said perhaps we need to instead add this type of info to [our section on critical errors](https://docs.particular.net/nservicebus/hosting/critical-errors?version=core_7)?

Thinking that we're now leaning more on the users to take action after some period of time so the CB pattern is still very relevant for them.

@Particular/sqlserver-transport-maintainers @Particular/nservicebus-maintainers thoughts?

**Comment by SzymonPobiega** [comment]
> Just noting that we're, albeit slowly, moving away from the Circuit Breakers

This is not documented anywhere. I thought we still recommend users to provide a sensible critical error handling action (kill the endpoint), just not doing it by default.

**Comment by andreasohlund** [comment]
> I thought we still recommend users to provide a sensible critical error handling action (kill the endpoint), just not doing it by default.

My point was that they wouldn't need to tinker with the CB any more. Eg. if the SQLT CB triggers after 2 mins (think that's the default). The users can just say,"ok, if not back to normal after 10 min I will kill the endpoint". Ie no need to configure the CB? (Unless I guess the current default is to long?)

**Comment by SzymonPobiega** [comment]
@andreasohlund not sure I follow. So if we remove this setting, how would I implement the usage scenario "if my SQL Server is down for 10 minutes, kill the endpoint"?

**Comment by andreasohlund** [comment]
> So if we remove this setting, how would I implement the usage scenario "if my SQL Server is down for 10 minutes, kill the endpoint"?

When Critical error triggers, set a timer on 10-2 minutes. If you haven't been able to process a message within this time then kill the endpoint.

I guess this makes it obvious that our API is pretty bad since we have no way of flagging that "the critical error situation have been resolved"?

**Comment by SzymonPobiega** [comment]
> I guess this makes it obvious that our API is pretty bad since we have no way of flagging that "the critical error situation have been resolved"?

Yeah. I think this is the reason to keep this config setting around until we have a better API that can inform the user when things OK again.

**Comment by andreasohlund** [comment]
Yea, makes sense now, thanks for making me realize it 👍

**Comment by weralabaj** [comment]
The documentation will be updated as a result of the discussion, so closing for now, this will be tracked elsewhere.
