### ISSUE TITLE
Code First API documentation

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#1178]
Background: We want to move away from custom ConfigurationSection sections to a Code First configuration API. (https://github.com/Particular/PlatformDevelopment/blob/master/designprinciples/nservicebus/discoverability.md#favor-code-first-configuration-apis)

Should we mention the move to the code first API somewhere on the docs page? I wanted to avoid to repeat a note/warning about it on every config section usage in the future.

This could include general guideline on how to access the config file programmatically to "reimplement" the existing config file support.

**Comment by weralabaj** [comment]
From what I see we follow quite a consistent approach in docos - we list all available config options, starting with code API (ex. here http://docs.particular.net/nservicebus/sqlserver/configuration).
If we remove custom config file options, then it'll be clear it's no longer supported, because there won't be a sample for it. We can then add snippet that shows how the same effect can be achieved using code (in the same section or another).
In my opinion that would be good enough and should be simple to implement.

@timbussmann do you think that addresses your concern or you had something more explicit in mind?

**Comment by timbussmann** [comment]
@weralabaj I'm good with that approach on the config related pages. I could imagine users having the question how to have a config based configuration with v6+ since that was possible previously. We should probably have a page about how to read the config file as a guide we can link users to?

**Comment by weralabaj** [comment]
@timbussmann do you still think this 

> We should probably have a page about how to read the config file as a guide we can link users to?

makes sense?

If so, can you take care of it?

**Comment by timbussmann** [comment]
I guess a sample would be the appropriate place to show this in case we don't already have one.
I can take care of it, but I can't give an ETA on it.

**Comment by weralabaj** [comment]
@timbussmann but isn't the reading from config file kind of a basic knowledge? I'm not sure if we need to show that. Or could we get away with a simple snippet?

**Comment by timbussmann** [comment]
closing this. So far the obsoletion note seems to be way docs maintainer agreed on and according to @weralabaj there doesn't seem to be interest in a sample.
