### ISSUE TITLE
Clarify Azure Storage Queues transport transaction options

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/docs.particular.net#1186]
ASQ transport configuration doco does not mention anything about [transport transaction modes](http://docs.particular.net/nservicebus/messaging/transactions). These need to be reconciled.

/cc @weralabaj @indualagarsamy

**Comment by indualagarsamy** [comment]
@SeanFeldman @yvesgoeleven @boblangley - Can you please comment on this issue on what the current modes are and what they mean, so we can capture them in doco? Thanks.

**Comment by yvesgoeleven** [comment]
ASQ supports:

- **Receive Only**: On receive asq will not remove the message from the queue, but hide it for 30 seconds so that other instances cannot pick it up. If the receiver fails to processes the message within that timeframe or actively abandons the message, then it will become visible again and another instance - **can pick it up**.
Unreliable: We actively delete the message from the queue after receive but before processing (usually not a good idea of course)

**Comment by weralabaj** [comment]
The issue was addressed by :
- Creating [transactions matrix](http://docs.particular.net/nservicebus/messaging/transactions#transactions-transaction-levels-supported-by-nservicebus-transports)
- Reviewing and updating content in the relevant section of the [ASQ transport doco](http://docs.particular.net/nservicebus/azure/azure-storage-queues-transport#transactions-and-delivery-guarantees)

I'm closing this issue.
