### ISSUE TITLE
Clarify Azure Service Bus transport transaction options

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/docs.particular.net#1187]
ASB transport configuration doco does not mention anything about [transport transaction modes](http://docs.particular.net/nservicebus/messaging/transactions). These need to be reconciled.

/cc @weralabaj @indualagarsamy

**Comment by indualagarsamy** [comment]
@SeanFeldman @yvesgoeleven @boblangley - Can you please comment on this issue on what the current modes are and what they mean, so we can capture them in doco? Thanks.

**Comment by yvesgoeleven** [comment]
ASB Supports

- **Unreliable:** Usinig ASB's ReceiveAndDelete mode, ASB actively deletes the message from the queue after receive (usually not a good idea of course)
- **Receive Only:** Using ASB's PeekLock mode, it  will not remove the message from the queue after receive, but hide it for 30 seconds so that other instances cannot pick it up. If the receiver fails to processes the message within that timeframe or actively abandons the message, then it will become visible again and another instance can pick it up.
- **SendAtomicWithReceive:** As from V6, and under the condition that the destination & receive queues/subscriptions are in the same namespace, ASB can support this mode. We do this using the 'ViaEntityPath' property on outbound messages and set it's value to the receive queue. If this property is set the messages will be added (but hidden) to the receive queue and only forwarded to it's real destination (inside the broker) when the complete operation on the received brokered message. If the 30 seconds are exceeded or the message is abandoned, the sent messages will not be forwarded.

**Comment by SeanFeldman** [comment]
Devil is in details: `SendAtomicWithReceive` would only work when sends and receive are in the same namespace. If these are different namespaces, it will not work.

**Comment by weralabaj** [comment]
The issue was addressed by :
- Creating [transactions matrix](http://docs.particular.net/nservicebus/messaging/transactions#transactions-transaction-levels-supported-by-nservicebus-transports)
- Reviewing and updating content in the relevant section of the [ASB transport doco](http://docs.particular.net/nservicebus/azure/azure-servicebus-transport#transactions-and-delivery-guarantees)

I'm closing this issue.
