### ISSUE TITLE
Documentation for Delayed Delivery is innacurate

### ISSUE THREAD

**Issue by WojcikMike** [Particular/docs.particular.net#1258]
Documentation for Delayed Delivery (http://docs.particular.net/nservicebus/messaging/delayed-delivery#delayed-delivery-timespan-v3_x-5_x) states:

"When a message is sent it does not need to be dispatched immediately. You can specify a later time for the message to be delivered. Before version 6 this was achieved by using bus.Defer(...)"

The above statements is innacurate as bus.Defer do not defer sending as stated above. It defers the handling of the message. Which for me is not clear from this site. 

The content that I would like to find on this page:
* What bus.Defer actually does
* How it uses TimeoutManager
* And information that the message is somewhere persisted

**Comment by mikeminutillo** [comment]
OK. I have verified that the current behavior makes it work exactly as you have outlined. I think this is actually a bug though. I would expect that `bus.Defer` will send the message as normal when the timeout is reached.  

The fix for https://github.com/Particular/NServiceBus/issues/2353 always overrides the address to be the local endpoint address. This was not the case before. Here is the offending commit: https://github.com/Particular/NServiceBus/commit/a6048e0bc9fc871c3397ad9e78cc0f0531800e5e

I wonder how many people are using `bus.Defer()` to send to another endpoint if this has been broken for over a year and no-one shouted at us.

@indualagarsamy @johnsimons @janovesk and @andreasohlund were all involved in this fix. Which is the intended behavior?

**Comment by johnsimons** [comment]
> I wonder how many people are using bus.Defer() to send to another endpoint if this has been broken for over a year and no-one shouted at us.

No one is using it because version prior to v6 do not support it.

**Comment by johnsimons** [comment]
> Which is the intended behavior?

We send it to the local timeoutdispatcher queue and then the timeoutmanager eventually dequeues it and send it to its destination.
Does this make sense ?

**Comment by mikeminutillo** [comment]
> We send it to the local timeoutdispatcher queue and then the timeoutmanager eventually dequeues it and send it to its destination.
> Does this make sense ?

It does make sense. That's not what it's doing. We send it to the local timeoutmanager which eventually dequeues it and sends it back to the originating sender.

**Comment by johnsimons** [comment]
> We send it to the local timeoutmanager which eventually dequeues it and sends it back to the originating sender.

That is what I said just in other words

**Comment by mikeminutillo** [comment]
> That is what I said just in other words

No it's not. Let's say we have two endpoints A and B. Message M is configured to be routed to B.

If A does `bus.Send(new M());` then the message will be delivered to `IHandleMessages<M>` inside of endpoint B.

If A does `bus.Defer(TimeSpan.FromSeconds(30), new M());` then in 30 seconds the message will be delivered to `IHandleMessages<M>` inside of **A**. I would expect it to go to B (as with a Send).

**Comment by johnsimons** [comment]
Yes that sounds like a bug in the core, raise an issue over there
