### ISSUE TITLE
ASB keep connectionstrings safe

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/docs.particular.net#1268]
Connects to https://github.com/Particular/PlatformDevelopment/issues/718

Document how to keep connectionstring safe from accidental leakage if communicating across untrusted boundaries, and what facilities are available to support this in v7 (namespace mapping)

- [ ] exchangeing logs
- [ ] message level

**Comment by weralabaj** [comment]
@SeanFeldman @yvesgoeleven could that be a starting point http://docs.particular.net/nservicebus/azure-storage-queues/configuration#connection-strings-securing-connection-strings?

**Comment by SeanFeldman** [comment]
@weralabaj yes, with changes. For example: 

> It is possible to accidentally leak sensitive information in the connection string if it's not properly secured. E.g. the information can be leaked if an error occurs when communicating across untrusted boundaries, or if the error information is logged to an unsecured log file.

It's not accurate. There are many ways to leak sensitive information. The doco is not about that. The doco about the fact NSB/transport **was** logging raw connection strings and that information was found in log files. From vNext it's changing to ensure better security. Every other way to leak info is out of scope since its not under our control.

**Comment by weralabaj** [comment]
Done
