### ISSUE TITLE
add cleanup strategy to databus sample

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#1462]

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers can you please prioritizes this in your todo list

**Comment by timbussmann** [comment]
@SimonCropp can you clarify what this issue is about in the description? Is this a task which can only be done by core maintainers?

**Comment by weralabaj** [comment]
@timbussmann the latest comment in referenced PR from @dvdstelt :

> @SimonCropp Now the cleanup strategy idea is in the v5 snippet, but not in v3 & v6?

Second snippet under this : http://docs.particular.net/nservicebus/messaging/databus#databus-attachments-cleanup-filesharedatabus

also https://github.com/Particular/docs.particular.net/pull/1335#issuecomment-214282833

So I guess the problem is the issue is relevant (desk questions, gg questions), but the involved people didn't have the full context to address this aspect. Does DataBus fall under core?

**Comment by danielmarbach** [comment]
@weralabaj @SimonCropp We had many discussions in the past around the feature and lack of features of the current Databus approach. We also have a few related issues in PlatformDevelopment around the databus but so far we didn't feel the need to prioritize those items from a company perspective. I suggest we rip the data bus functionality out of the core and make it a dedicated evolvable piece like what we are currently doing with the WCF support.

**Comment by weralabaj** [comment]
This issue is only about documenting guidance for cleanup strategy. I don't have context for those other issues.

But are you just saying that we're pinging the wrong people? ;)

Given that it's useful from customers perspective, how can we do it at least for v6?

**Comment by SimonCropp** [comment]
related https://github.com/Particular/docs.particular.net/issues/1402

**Comment by SimonCropp** [comment]
@dvdstelt since u did this https://github.com/Particular/docs.particular.net/pull/1335  do u want to have a go at applying it to the sample?

**Comment by dvdstelt** [comment]
@SimonCropp Sure, I will have a look at it

**Comment by SimonCropp** [comment]
just added a link here instead https://docstest.particular.net/nservicebus/messaging/databus/file-share#cleanup-strategy
