### ISSUE TITLE
Getting started guide is not a tutorial but a sample - First time user expiriance

### ISSUE THREAD

**Issue by sfarmar** [Particular/docs.particular.net#1521]
I got this email from a customer trying to get started with NServiceBus.
I think we can improve this?

**Comment by SimonCropp** [comment]
That sample has not really changed much since v3 days. I agree it is lacking

In regards to his question it seems like this is actually the sample that would have helped more http://docs.particular.net/samples/endpoint-configuration/

**Comment by weralabaj** [comment]
@sfarmar I moved your description to DevEdu, to avoid making conversation with customer public ;)
let's close issue here and discuss there?

**Comment by goblinfactory** [comment]
Thank you for the quick response. I have enough to work with now, thank you. Last bit of constructive feedback; I highly recommend Particular do some hallway testing on your documentation; get 2 or 3 .net volunteers who have never used nservicebus before and ask them to go to your website and find the 'getting started' and follow the instructions. you'll get a world of useful feedback. All the best, Alan

**Comment by sfarmar** [comment]
@weralabaj you beat me to it, thanks.

@goblinfactory Thanks for the feedback

**Comment by weralabaj** [comment]
@goblinfactory The timing is really good, since we're about to start a larger initiative to improve the experience for 1st time users. I guess a lot of "new" people coming to our website went through the course or the book, so we don't get a lot of feedback from people starting from the website.
We really appreciate your comments. If anything new comes to mind, please, email Sean or raise an issue in this repository and we'll look into that.

**Comment by weralabaj** [comment]
@goblinfactory We've updated the step by step sample, please let us know if you think it's better now http://docs.particular.net/samples/step-by-step/. Thanks again for your feedback!
