### ISSUE TITLE
Suggestion: Examples and suggestions for async handlers

### ISSUE THREAD

**Issue by janpieterz** [Particular/docs.particular.net#1563]
A couple of quick examples of how to handle the async handlers, what patterns you guys see as valuable (I saw you use .ConfigureAwait(false) quite a lot in the NSB code, for example), how to handle synchronous third party calls efficiently according to the NSB pipeline.

More or less an extension/renewal of [this blog post](http://particular.net/blog/async-await-its-time), but then incorporated in the official docs (and with the new, official API), plus maybe you guys' insight after building such a massive system async.

**Comment by danielmarbach** [comment]
@janpieterz Thanks for your suggestions. We will be looking into it. About

>  plus maybe you guys' insight after building such a massive system async.

We'd consider this type of content mostly content for blog posts and webinars. Part of that experience has already been published for example as

http://particular.net/webinars/async-await-best-practices
http://particular.net/blog/the-dangers-of-threadlocal

I'm also giving a talk at NDC Oslo

http://ndcoslo.com/talk/rearchitect-your-code-towards-async-await/

I'll keep you posted when the talk is online.

**Comment by janpieterz** [comment]
Superb, would love to hear that talk (plus I'll check the webinar again).

**Comment by danielmarbach** [comment]
@janpieterz I opened up https://github.com/Particular/docs.particular.net/pull/1567

Would you like to provide feedback whether the sample snippets would make sense? Is something missing? Please bear in mind that the roughly outlined snippets are in draft, and we might end up with different snippets or be leaving out a few.

**Comment by janpieterz** [comment]
That looks good! Maybe there is a slight bit of replication but not sure if that is such a bad thing.

I admit I haven't gone to deep into it myself, but it might be good to know the difference between (https://github.com/Particular/docs.particular.net/pull/1567/commits/7b0ea1ae5878d3bada9d75b3194ae8c1774b6745#diff-3c6bed0a6ddb3e150980b3a2dd1d3252R42) and (https://github.com/Particular/docs.particular.net/pull/1567/commits/7b0ea1ae5878d3bada9d75b3194ae8c1774b6745#diff-3c6bed0a6ddb3e150980b3a2dd1d3252R52).

Also, maybe this is a bit too much for my specific use case, but I have an external SDK that if something goes wrong in the connection it times out after more than 30 seconds. I see that a Task.Run is used (https://github.com/Particular/docs.particular.net/pull/1567/commits/7b0ea1ae5878d3bada9d75b3194ae8c1774b6745#diff-3c6bed0a6ddb3e150980b3a2dd1d3252R25) for a blocking > 300 ms run. Would a similar method be used for something like a possible 30 second timeout? 

Also, https://github.com/Particular/docs.particular.net/pull/1567/commits/7b0ea1ae5878d3bada9d75b3194ae8c1774b6745#diff-3c6bed0a6ddb3e150980b3a2dd1d3252R97 and https://github.com/Particular/docs.particular.net/pull/1567/commits/7b0ea1ae5878d3bada9d75b3194ae8c1774b6745#diff-3c6bed0a6ddb3e150980b3a2dd1d3252R97 seem to have their name reversed from my understanding? Batched seems to send right away while the Immediate seems to make an array of messages and then waits all at the end, or I might have to really start spending some learning time.

**Comment by danielmarbach** [comment]
@janpieterz I took the liberty to edit your comment and assign letters to the paragraphs so that I can refer it here in this conversation.

(A) The idea is to show how this affects the statemachine generation. In short when you return the task, then you don't mark the method as async. The implications are the compiler will not generate a statemachine and you safe the "overhead" of the statemachine code during runtime as well as state allocations which happen before the continuation (save state) and after the continuation (restore state). The final version will have this typed out. See https://github.com/danielmarbach/02-25-2016-AsyncWebinar/blob/master/webinar/Script.cs#L115

(B) Would you like to put some kind of SLA in place? So for example if the method doesn't return after 20 seconds you want to abort and retry? I can definitely add such an example if you explain a bit more your ideas.

(C) By default if you don't specify `RequireImmediateDispatch` the messages will not go out when you call context.Send. They will go out after all handlers have completed successfully. Here some doco around that behavior.

http://docs.particular.net/nservicebus/messaging/batched-dispatch
http://docs.particular.net/nservicebus/messaging/send-a-message#dispatching-a-message-immediately

**Comment by janpieterz** [comment]
That certainly makes it clearer, thanks.

(A). Thanks! I'll have to look into this more, is this handled in the NSB webinar you linked before? Got some time at the end of the week planned to dive into it. Certainly underestimated the amount of stuff that is just slightly different and good to know, but happy I'm doing it now.

(B). So in my case I have a synchronous SDK to  a third party. A message comes in, I try to connect, happy flow this connects in say a second or something, does something for 5 seconds and returns data that will result in new messages published. Bad flow will result in a timeout after > 30 seconds that 'should' result in a message send that the connection failed and marks this specific connection as 'dead' in our system. 

For clarity, these external connections can count up to 300+ different ones, and the goal is (besides retrieving data and executing actions on those connections) to monitor the state and have a knowledge within this application that the connection is down (for example the internet is down etc) and allow notifications to operators. 

The 30 seconds comes close to / over the message timeouts I think, so I'll have to extend those, but I think for this discussion it's more about how to handle such a case with NSB and the async stuff, is it a task that runs (it will always return, either by throwing a connection exception that I catch or by a good result), is it just a call I do without a task etc.

I made a very quick pseudo-gist that shows, more or less, what I imagine would happen. All the calls to SiteProvider and the connection it returns are sync by their dependence on that external party's SDK. 
https://gist.github.com/janpieterz/cdaf564e99ae9185c80e4e557ec75a5f

(C) Ah, so for my understanding, if in the `ImmediateDispatchHandler` the `RequireImmediateDispatch` was removed, the behavior goes back to being batched? So the await on the context sending is technically more 'await that it is batched in the transaction'?

Thanks for your input and assistance on this, sorry if I'm dragging stuff out that is in the webinar, if so, just skip it since I'll check it soon!

**Comment by danielmarbach** [comment]
(B) I forked your gist, see the example https://gist.github.com/danielmarbach/3031de0986e9b3e874cf74f607bce0c0 the trick is to rearrange your code slightly. Separate compute bound things from IO-bound things (I'll show this in my NDC talk ;) )

(C) Yes. Except that the meaning is more: await until the outgoing pipeline which takes care of batching is done. Because in practice you could extend that batching pipeline with additional IO-bound work.

Hope that helps. Btw. Don't worry. You are not dragging stuff out. I'm here to help

**Comment by janpieterz** [comment]
Thanks, both are cleared up and the gist is very insightful!

**Comment by danielmarbach** [comment]
@janpieterz do you want to have a look at http://docs.particular.net/nservicebus/handlers/async-handlers and tell me if that answers most of your desires or if there is anything missing? If everything is ok I'm going to close this issue

**Comment by danielmarbach** [comment]
@indualagarsamy sure

https://vimeo.com/172111826

**Comment by janpieterz** [comment]
@danielmarbach that seems like an extremely solid piece, combining all of the stuff I can think off in one place. Thanks, that must have been quite the effort!

**Comment by danielmarbach** [comment]
@janpieterz glad that you like it! Documentation is worth the effort. It forces us to think and express the scenarios we see. We found many subtle issues while documenting things.
