### ISSUE TITLE
MsmqPersistence: TimeoutPersisterReceiver Failed to fetch timeouts from the timeout storage

### ISSUE THREAD

**Issue by elshev** [Particular/docs.particular.net#1604]
Have a NullReferenceException for Msmq persistence. 

NServiceBus: 5.2.14
Windows 10

**Steps to reproduce:**
1. Download Step By Step example
2. Change InMemoryPersistence to MsmqPersistence in all projects
3. Run and get error:
2016-06-17 10:08:14.848 WARN  NServiceBus.Timeout.Hosting.Windows.TimeoutPersisterReceiver Failed to fetch timeouts from the timeout storage
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.Timeout.Hosting.Windows.TimeoutPersisterReceiver.Poll(Object obj) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Timeout\Hosting\Windows\TimeoutPersisterReceiver.cs:line 90
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

I've read discussions in google groups and here about this error but still have no idea what to do. This error appears in my solution also.

**Comment by timbussmann** [comment]
Hey @elshev 

MsmqPersistence actually only stores subscriptions, so it's not a standalone persistence options if you're using timeouts, sagas or the outbox.

The problem is, that timeouts are enabled by default and you're seeing this exception because there is no timeout persistence available.

On your sample you can fix this in two ways:

* Disable the timeout manager (since you're not using any timeouts) and configure the MsmqPersistence:

```
busConfiguration.DisableFeature<TimeoutManager>();
busConfiguration.UsePersistence<MsmqPersistence>();
```

* Configuring the InMemoryPersistence for the timeout storage and MsmqPersistence for the subscriptions:

```
busConfiguration.UsePersistence<InMemoryPersistence, StorageType.Timeouts>();
busConfiguration.UsePersistence<MsmqPersistence, StorageType.Subscriptions>();
```

The error you're seeing is definitely not helpful and we improved this for version 6 of NServiceBus to give you a proper error message at startup time. It looks like the documentation also isn't very clear about the capabilities and the usage of the `MsmqPersistence` and I'll have a look how we can improve it.

Please let me know whether the suggested solutions work for you!

**Comment by elshev** [comment]
Thanks @timbussmann !!!
The explanation is clear and helpful.
It works for me in test solution and in my solution too.

**Comment by timbussmann** [comment]
Glad to hear you were able to get it working! :+1: 
I've raised a pull request to make the documentation a bit clearer (also regarding the impact of disabling the timeout manager) here: https://github.com/Particular/docs.particular.net/pull/1605 Feel free to review the proposed changes and see whether that would have helped you.
