### ISSUE TITLE
Make AAA style testing more prominent on testing page

### ISSUE THREAD

**Issue by danielmarbach** [Particular/docs.particular.net#1829]
Based on https://github.com/Particular/NServiceBus.Testing/issues/90#issuecomment-243380979 I think we should make AAA style testing more prominent on the main testing page. For example first show a quick example of AAA style testing with further information link to the sample page and then show the fluent style syntax. Thoughts @Particular/docs-maintainers ?

**Comment by SimonCropp** [comment]
sounds good to me

**Comment by weralabaj** [comment]
@danielmarbach do you think that this issue could be addressed by having version switching for this page, rather than a dedicated page for v6 (which is a sample, sigh....)?

IMO that would be simpler. see related https://github.com/Particular/docs.particular.net/issues/1746, didn't manage to get to it before vacation though :)

**Comment by danielmarbach** [comment]
Not sure @weralabaj. As far as I understand version switches is that they should be used if the content of the snippet is similar. But here I'm talking about revamping the page to show AAA style testing first and make it more prominent.

**Comment by SimonCropp** [comment]
@danielmarbach 

> As far as I understand version switches is that they should be used if the content of the snippet is similar.

nope. some pages switch all (or almost all) their content. eg https://docs.particular.net/nservicebus/messaging/routing-extensibility

**Comment by danielmarbach** [comment]
Ok then I'm fine with that approach
