### ISSUE TITLE
Improve doco on transactions regarding Receive and Atomic modes in V5

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1833]
The documentation states that _Sends atomic with Receive_ is present in V5 which is partially true and the same for _Receive_ the transport decides the mode.
### ReceiveOnly: Rabbit, ASQ, ASB

Rabbit, ASQ, ASB will only support ReceiveOnly.
### Enlistment: ASQ, ASB

Enabling distributed transactions results in ReceiveOnly but the transports will use transaction enlistment to achieve batched send like behavior where the messages are transmitted after all processing completes which minimized 'ghost' messages.
### Atomic: MSMQ, SQL

MSMQ and SQL do not support ReceiveOnly in V5. Sends are always part of the receiving transport transaction. Maybe only when wrapping the sends in a TransactionScope RequiresNew/Suppress can result in that behavior.
## References
- http://docs.particular.net/nservicebus/transports/transactions#transactions-transport-transaction-sends-atomic-with-receive
- https://particularsoftware.slack.com/archives/engineering/p1472630521000166

**Comment by weralabaj** [comment]
@ramonsmits is it about providing content for http://docs.particular.net/nservicebus/transports/transactions#TODO? :P

That's the link for "Transport Transaction" in a table for v5.

Since it's different for specific transports, would it make sense to cover it in more detail in pages dedicated to transports rather than the shared page? (e.g. http://docs.particular.net/nservicebus/azure-storage-queues/transaction-support#transactions-and-delivery-guarantees or http://docs.particular.net/nservicebus/rabbitmq/transactions-and-delivery-guarantees)

Then in the main document we could just mention that for details you need to refer to documents specific for the selected transport.

**Comment by ramonsmits** [comment]
@weralabaj Seems my original link died as the anchor isn't present anymore. Now seems to be http://docs.particular.net/nservicebus/transports/transactions?version=Core_6#transactions-transport-transaction-sends-atomic-with-receive

So this is not present anymore for V5 making this issue maybe now irrelevant but just see something else

For V5: http://docs.particular.net/nservicebus/transports/transactions?#transactions-transport-transaction-consistency-guarantees

> Not all the transport support batched dispatch

Batched dispatch is a V6 feature, now mentioned in V5 doco? Not sure if this is correct. Although in V5 using ASB uses transaction enlistment to get similar behavior.

**Comment by weralabaj** [comment]
@ramonsmits sounds like the simplest thing to do would be to review that page for all versions and make sure it's accurate & raise PR with edits if necessary, can you do that?

**Comment by weralabaj** [comment]
@ramonsmits ping ☝️

**Comment by SimonCropp** [comment]
@ramonsmits if you ever get around to this please submit a PR
