### ISSUE TITLE
Give more attention to our google groups

### ISSUE THREAD

**Issue by johnsimons** [Particular/docs.particular.net#184]
The homepage seems to be giving more relevance to SO then our own google groups which IMO are a lot better.

**Comment by sergioc** [comment]
@johnsimons can you explain why you think SO has more relevance in that page?

**Comment by indualagarsamy** [comment]
@sergioc : Originally I think the idea was that the SO is a dev forum, and we had topics there. However, since SO has restrictions on how we post our answers, for e.g., a link to our doc site is not a "good answer" from SO's perspective, etc, it might be better to promote our forum.

**Comment by SimonCropp** [comment]
ok so i have already removed 3 of the links to Stackoverflow. so only one remains. I also listed the last remaining link after "Discussion group".

As for still more prominence i think the "Discussion group" should be listed higher than "Hands-on labs".  So I propose 

 * Switch the locations of the "Hands-on labs" and "Discussion group"
 * rename "External training resources" to "Other resources" and remove the text "Community help"

Any objections?

**Comment by johnsimons** [comment]
I would remove the last stackoverflow link

**Comment by SimonCropp** [comment]
@johnsimons no objections here. if no one else chimes in I will remove it

**Comment by sergioc** [comment]
I don't agree with just removing these links based on opinions without first checking Analytics and how actual traffic looks like from docs home to to Google Groups and SO. Also, if you remove the link to SO, then the only page left linking to SO is the Contact page.

I haven't seen any hard evidence here indicating that the SO link is harming traffic flow to Google Groups. Only way to find that out without asking users is by attaching Google Analytics events to those 2 links.

Because I understand the initial concern and the fact that metrics analysis needs time for analysis, I agree with @SimonCropp's proposal in https://github.com/Particular/docs.particular.net/issues/184#issuecomment-68930725, but at the moment I don't see reason to agree with removing the link to Stack Overflow, as suggested by @johnsimons in https://github.com/Particular/docs.particular.net/issues/184#issuecomment-69275364.

@SimonCropp Google Groups larger icons:

![discussion](https://cloud.githubusercontent.com/assets/493451/5680983/4169cd7c-9814-11e4-9ff6-3c55198cd204.png)

![discussion-hover](https://cloud.githubusercontent.com/assets/493451/5680986/46e390d0-9814-11e4-9679-4999a27e3ca0.png)

**Comment by SimonCropp** [comment]
done

**Comment by sergioc** [comment]
@SimonCropp noticed that the titles "External training resources" and "Community help" (to be replaced with "Other resources") are missing:

![2015-02-02 at 14 38](https://cloud.githubusercontent.com/assets/493451/6001373/71463994-aae9-11e4-8abe-0249a6b719f2.png)

**Comment by sergioc** [comment]
@SimonCropp when hovering the "Discussion group" icon, the icon shifts to the side on hover - can you check?

**Comment by SimonCropp** [comment]
@sergioc 

> when hovering the "Discussion group" icon, the icon shifts to the side on hover

Fixed

> the titles "External training resources" and "Community help" (to be replaced with "Other resources") are missing

Yes.

* "Community help" made no sense for Hands on labs
* If the above links need no description then neither do the below links
* they were using vertical space for no reason. It is clear what those links are without the extra text
