### ISSUE TITLE
Feature request: Last changed documentation

### ISSUE THREAD

**Issue by christoffer-lundqvist** [Particular/docs.particular.net#1883]
In order to stay updated on the latest changes in the product suit, it would be nice to be able to see what documents/links that have been changed in i.e the last week or days.

**Comment by indualagarsamy** [comment]
Hi @christoffer-lundqvist - Thank you for you suggestion. I'll raise it internally to see what the other maintainers of this repository think. 

However, I think that even now, you can get to the history of changes, since all our documentation resides on a public github repository. 

For instance, say, you'd like to see the history for an article: 
http://docs.particular.net/nservicebus/sagas/

You can go to GH, 
- https://github.com/Particular/docs.particular.net/blob/master/nservicebus/sagas/index.md
(You can also get here by clicking on the green `Edit` button, which will open up the appropriate document in Github and then you can click `Cancel` to get out the editing)
- From here, clicking on the `History` button will show you all the commits related to the documentation and you can have a lot more details about the document you are viewing. 

Also, lots of changes are done to our documentation on a daily basis. So if we had a list for this, it would feature a long list.  In addition to adding docs, we also review the docs. When you look at an article in GH, as I explained in the previous step, in the document title, there is column called `reviewed`, which also gives you a sense of when the document was reviewed by one of the @Particular/docs-maintainers.  
 
Hope this helps. Thanks again.

**Comment by weralabaj** [comment]
Sounds like some kind of a "periodic digest" thing, is that right @christoffer-lundqvist?

At the moment I don't think we have a good tool to differentiate between "trivia" changes (like fixing spelling mistakes, light editing without changing the contet, etc.) and important updates (other than related to the release).

Could you please clarify of why would that be useful and how it would help you? What kind of changes will be of interest? Are you following announcements on the GoogleGroup? What do you think is missing in what we already do in announcements? 

Maybe more details will insipre a new idea :)

**Comment by christoffer-lundqvist** [comment]
Hi,

As a system architect I more than once a week browse the online
documentation for a quite a few different reasons.

Most of the times we use the documentation in order to be able to
understand new features in minor patches. We upgrade SC and SP all the time.
Most of the time we just read the commit notes and what issues are being
resolved, and that nice.

Instead of just watching (monitoring) your new releases and reading patch
notes I want to keep track of what has changed in the documentation.
Because you learn more about the product each time you read the docs and
you might discover features you didn't now existed if you study the docs
once a week.


Each time you release a minor patch and you also changed the documentation
you could could publish an event containing the URL and section #bookmark)
that was changed.

It's more about that I want to be DRAWN to the docs, just like my iPhone
has a red notification indicator for an app. The docs app can subscribe to
the doc changes maybe :) The more you read docs the more you learn about
NServiceBus. Right now it's hard to know what parts of the has been changed.

Sorry for the unstructured answer...





Updated service control docs



But sometimes everything is

**Comment by weralabaj** [comment]
Thanks @christoffer-lundqvist ! 

That helps a lot :)

**Comment by weralabaj** [comment]
@christoffer-lundqvist After discussing various options, we thought the good idea would be to include link to relevant documentation pages in the release notes. That would have to be done manually, but we could make sure it's easy to get more context regarding changes and not overwhelm anybody with (mostly) irrelevant information.

What do you think?

**Comment by christoffer-lundqvist** [comment]
Thanks. That would be a good start I think.
