### ISSUE TITLE
Would you tell me how to build the website like (http://docs.particular.net/)

### ISSUE THREAD

**Issue by fangqifan** [Particular/docs.particular.net#1917]
Hi @weralabaj !,I find that the chinese document of NServiceBus on the internet is rare. I plan to build an website  which I can translate document into Chinese to share on internet. Now, I have translated some articles. Would you tell me how to use this repository to build the website like (http://docs.particular.net/) ? 
Thanks.

**Comment by weralabaj** [comment]
Hi @fangqifan,

I'm not sure if I understand you correctly, but do you want to create a chinese version of our documentation?

I think the simplest thing to do would be to set it up using some existing CRM or documentation tool. We have an interal documentation engine, but that will be probably an overkill unless you translate a lot of the content and plan to keep it in sync with the official documentation (updating periodically).

Could you clarify what you have in mind?

Thanks,
Weronika

**Comment by fangqifan** [comment]
Hi @weralabaj

As you know, I want to create a Chinese version of your documentation, and plan to keep it in sync with the official documentation by updating it periodically. I have bought a domain (http://nservicebus.cn) and have uploaded a small set of translated documents. Unfortunately, we have to address many formatting issues in translation because the current version of this website is based on GitBook engine. Therefore, It would be awesome if you are willing to share your documentation engine, which will definitely save us a tremendous amount of efforts. Meanwhile, I have shared my experience with my friends about establishing the Chinese version of this documentation, they all get interested and they are eager to participate . 

Thanks,
Fangqifan

**Comment by SimonCropp** [comment]
@fangqifan 

While we appreciate the proactive attitude there are complexities with having a fork of the documentation in a different language. 

 - There is a significant amount of time and effort that goes into maintaining our documentation since it very much a living body of content. It would take a third party a significant amount of time and effort on a continual bases to keep up to date with the main fork
 - We currently have no mechanism in place to communicate the types and  scope of the various documentation changes. so some process would be need to put in place.
 - Some documentation publication is timed carefully to coincide with various other efforts in the company. This would be difficult to keep in sync with an external fork
 - Some documentation has legal ramifications and needs to be worded and reviewed carefully eg https://docs.particular.net/nservicebus/upgrades/release-policy and https://docs.particular.net/nservicebus/upgrades/support-policy
 - we would need to revisit the license for the content https://github.com/Particular/docs.particular.net/blob/master/license.md#content-licensed-under-the-apache-license-version-20

With all these in mind I cant help but think that any fork of our documentation, that is not actively maintained by Particular, would very quickly fall out of sync. Then the questions is how valuable is a translation if it is not accurate or up to date with the english version.

Would it not be better to leverage something like google translate to perform automated translation on the current content? I realize the quality would not be as good as a manual translation but it would be much less effort in both the short and long term.

![image](https://cloud.githubusercontent.com/assets/122666/18812421/3fea4c2a-8317-11e6-8173-4fd3c2eca144.png)

**Comment by weralabaj** [comment]
@fangqifan since we don't have any Chinese speakers in the company so we won't be able to assist you, and as far as I know we don't have customers in that area, could you explain what you think is most important content to be translated?

Since translating everything will be a huge effort, as Simon noted above, maybe we could help you narrow down the most crucial pieces (in our opinion at least). Then if it turns out there's a big interest we can discuss what would be the best course of action going forward.

How does that sound?

**Comment by SimonCropp** [comment]
@fangqifan any thoughts on the above?

**Comment by SimonCropp** [comment]
@fangqifan closing this for now. please feel free to contact me directly if you want to discuss in more detail (simon.cropp@particular.net)
