### ISSUE TITLE
Feedback: Publishing from Web Applications

### ISSUE THREAD

**Issue by ralbu** [Particular/docs.particular.net#1995]
Page: /nservicebus/hosting/publishing-from-web-applications.md

It's not clear what 'Subscription Manager Endpoint' should be. Does that mean that I need to have one endpoint with no handlers for 'Subscription Manager Endpoint' and another End Point for the Subscriber?

Is this setup what I should be aiming to?
1. WebApp with a DB persistence and Message Endpoint pointing to a Subscription Manager Endpoint, like this:
```    
<MessageEndpointMappings>
      <add Messages="Shared" Endpoint="SubscriptionManagerEndpoint" />
</MessageEndpointMappings>
```
2. The Subscription Manager Endpoint with no handlers but with the same DB persistence as 1)
3. The Subscriber end point with InMemoryPersistence (or DB) and Message Endpoint pointing to a Subscription Manager Endpoint, like this:
```
<MessageEndpointMappings>
      <add Messages="Shared" Endpoint="SubscriptionManagerEndpoint" />
</MessageEndpointMappings>
```

**Comment by DavidBoike** [comment]
Hi @ralbu,

The "subscription manager" endpoint could be a special endpoint with no handlers, or an endpoint that handles other stuff that you've designated to be the subscription manager for other events published by the web tier servers. The important thing is only that it shares the same subscription storage.

It's important to break up your messages a little bit and not put them all in an assembly named `Shared`. 

The webapps need to be configured with database persistence. Since they are doing the publishing, and not subscribing to anything (at least in this example) they would not need MessageEndpointMappings at all.

The Subscription Manager endpoint also is not subscribing to anything. It would need to be configured for database persistence (same database) but also does not need MessageEndpointMappings.

Assuming the Subscriber isn't going to publish anything, it doesn't need subscriptions storage at all. But it does need a handler for `SomeMessage` and MessageEndpointMappings for it:

```
<MessageEndpointMappings>
    <!-- Could use this -->
    <add Messages="ServiceName.Contracts" Endpoint="SubscriptionManagerEndpoint" />

    <!-- Or this, more specific -->
    <add Messages="ServiceName.Contracts.SomeMessage, ServiceName.Contracts" Endpoint="SubscriptionManagerEndpoint" />
</MessageEndpointMappings>
```

Remember that an endpoint will send a subscription request when it 1) contains a message handler for an event type, and 2) knows where to send the subscription request from the MessageEndpointMappings.

Does that help?

**Comment by ralbu** [comment]
Hi David,

Thanks, that makes sense. The Shared assembly was just to make my point but I do break messages.
The book is very helpful, thanks for that.
