### ISSUE TITLE
Howto: custom set MessageID (by NSB users)

### ISSUE THREAD

**Issue by dannycohen** [Particular/docs.particular.net#204]
https://github.com/Particular/NServiceBus/issues/1779#issuecomment-35666137

**Comment by mauroservienti** [comment]
Add it to the [FAQ section](http://docs.particular.net/nservicebus/#faq)

**Comment by SimonCropp** [comment]
this is not a frequent question

**Comment by mauroservienti** [comment]
absolutely not, do you suggest to avoid to document it?

**Comment by SimonCropp** [comment]
I am making no assertion about if it should be documented or not. i just dont like the approach of "because the title happens to be phrased as a question it should be a FAQ". Many of our FAQs are actually "we have no idea where this should go or were to lazy to work that out so we will dump it here" eg how is this an FAQ http://docs.particular.net/nservicebus/dtcping-warning-the-cid-values-for-both-test-machines-are-the-same

**Comment by mauroservienti** [comment]
totally agree that FAQs are a mess right now :-) there is #219 to track that they are a mess, we need to re-organize the entire FAQ / HOW-To content. Personally to me FAQ are useless in the context of guidance/doco/api doco, I prefer how-tos as a general concept
