### ISSUE TITLE
Feedback: Moving away from IBus in Version 6

### ISSUE THREAD

**Issue by MeTitus** [Particular/docs.particular.net#2224]
Page: /nservicebus/upgrades/5to6/moving-away-from-ibus.md

Should this code:

var endpointInstance = await Endpoint.Start(endpointConfiguration)
    .ConfigureAwait(false);
IMessageSession messageSession = endpointInstance;
await messageSession.Send(new SomeMessage())
    .ConfigureAwait(false);

Be something like this instead:

var endpointInstance = await Endpoint.Start(endpointConfiguration)
    .ConfigureAwait(false);
IMessageSession messageSession = endpointInstance;
await messageSession.SendAsync(new SomeMessage(), token)
    .ConfigureAwait(false);

Why is a awaitable method not name with and async sufix and why doesn't it accept a cancellation token?

**Comment by SimonCropp** [comment]
@MeTitus 

> Why is a awaitable method not name with and async sufix

We did consider this but after much deliberation we decided to drop the async suffix. the reasoning is here https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix

> why doesn't it accept a cancellation token

The current state of cancellation token overloads is covered here https://github.com/Particular/NServiceBus/issues/3785

**Comment by MeTitus** [comment]
Well Microsoft does it, so why not follow the standard and come up with your own thing? Whatever the reasoning is, it just doesn't make any sense, and yes I did read the link you post which.

http://stackoverflow.com/questions/14652773/is-the-async-suffix-required-in-the-name-of-an-async-asp-net-mvc-4-action

It's a convention use it.

**Comment by SimonCropp** [comment]
@MeTitus 

When building any software it is important to understand any advice/conventions before making decisions based on it or following it. In this case there is no more reasons other than "because microsoft said so". given the other negatives in following that approach we decided to not follow the convention. It should also be noted that the async suffix convention conflicts with microsoft own convention of not using hungarian notation. eg members that return a thread do no suffix with "Thread". 

I see u referenced MVC, in that context there is good example of a poor MS convention in their MVC guidance. I most samples/communication/default conventions MS groups files in a project by category and not business function. so all controller in the same folder. all views in another folder. This is manageable for trivial examples but quickly becomes difficult in any real world usage. 

 * http://softwareengineering.stackexchange.com/questions/310833/why-does-everyone-put-controllers-in-one-folder-and-views-in-another
 * https://www.gurustop.net/blog/2012/09/11/aspnetmvc4-application-structure-by-features-move-views-by-area/
 * http://haacked.com/archive/2008/11/04/areas-in-aspnetmvc.aspx/

So be careful of following "It's a convention use it." without fully understanding the long term ramifications. 

No async suffix was our decision for v6, it is too late to change that in the current release since it is a breaking change. based on feedback (like this) we can always re-evaluate in v7. 

I will close this issue, since it is not really a docs problem. if u want to take this conversation further please raise an issue here https://github.com/Particular/nservicebus

And thank you very much for the feedback. We appreciate these kind of exchanges even when it is someone disagreeing with us or pointing out what we have possibly done wrong.

**Comment by MeTitus** [comment]
>  be careful of following "It's a convention use it." without fully understanding the long term ramifications.

What kind of sentence is that? Do you know what I know, where I have worked, the experience I have and so on to say something like that?

I hate it when people go personal for no good reason. I know all the long term ramifications way more than you it seems, since your justification for not following a convention is full of trash. You do know that .NET Core relies heavily on async methods right? I work with so many libraries and NServiceBus chooses not to follow a convention used in a platform they use to build their libraries. 

I tell you this much. Patterns, conventions and so on exist so that we developers can understand what we do, you follow them not because you have to, but because that's what the good practices say so.

Also, you look dumb when you complain about MS not following their own standards, which is exactly what you are doing and I challenge you to tell me of any other known library which does the same as you do... but maybe just maybe you should move sides and start porting your library to some other platform no since Microsoft is so bad?

As an example of how flawed your async implementation is, just look into this:

`        [HttpDelete]
        [Route("mealOrders/{orderId}/items/{itemId}")]
        public async Task RemoveItemFromOrder(int orderId, RemoveItemFromOrderMessage message, int itemId, CancellationToken token)
        {
            await _messageSession.Send(Mapper.Map<RemoveItemFromOrderCommand>(message));
        }

What do you do with the CancellationToken , do you just ignore it? Oh boy...`

**Comment by MeTitus** [comment]
https://msdn.microsoft.com/en-us/library/mt674882.aspx#Naming Convention

It's worth a read.

**Comment by weralabaj** [comment]
@MeTitus 

> What kind of sentence is that? Do you know what I know, where I have worked, the experience I have and so on to say something like that?

It's an unfortunate phrase, but I'm sure Simon didn't mean to imply anything personal. Note that right after he said:

> No async suffix was our decision for v6, it is too late to change that in the current release since it is a breaking change. based on feedback (like this) we can always re-evaluate in v7.
> I will close this issue, since it is not really a docs problem. if u want to take this conversation further please raise an issue here https://github.com/Particular/nservicebus
> And thank you very much for the feedback. We appreciate these kind of exchanges even when it is someone disagreeing with us or pointing out what we have possibly done wrong.

which much better reflects our stance. So apologies for misunderstanding, but it's just not well thought out bunch of words, not intentional personal remark.

> I challenge you to tell me of any other known library which does the same as you do... 

We listed a couple of examples here https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix#other-libraries-with-no-async-suffix.

In this article we also listed the whole reasoning behind this decision. I can assure you it wasn't an easy one, and we discussed it a lot internally. For better or worse, this is what was done, and we did our best to explain why.

I hope that sufficiently addresses your concerns.

**Comment by distantcam** [comment]
> By convention, you append "Async" to the names of methods that have an async modifier.

[https://msdn.microsoft.com/en-us/library/mt674882.aspx#Naming Convention](https://msdn.microsoft.com/en-us/library/mt674882.aspx#Naming Convention)

> X DO NOT use Hungarian notation.

[https://msdn.microsoft.com/en-us/library/ms229045(v=vs.110).aspx#Word Choice](https://msdn.microsoft.com/en-us/library/ms229045(v=vs.110).aspx#Word Choice)

These suggestions from Microsoft don't agree with each other.

**Comment by MeTitus** [comment]
@weralabaj Maybe you're right, maybe he did not choose the right words, either way it sound a tad arrogant.

@distantcam Well that applies to different things. Microsoft does not recommend Hungarian notation but for a specific set of functionality/pattern it recommends the use of and "Async" sufix, which sounds very reasonable to me. Given the broad usage of async methods within the .NET Core it will look strange, to say the list, that NServiceBus won't be aligned with the rest.

**Comment by MeTitus** [comment]
You should also either remove or update the documentation in here:

https://particular.net/blog/async-await-its-time

Also, since all the handlers are now async even if there are not reason to, we end up with this mess:

        public Task Handle(IPatientAdmitted message, IMessageHandlerContext context)
        {
            _patientInfoRepository.Add(new PatientInfoEntity
            {
                PatientId = message.PatientId
            });

            return Task.FromResult(true);
        }
