### ISSUE TITLE
Move to consistent phrasing in tutorials

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#2238]
https://docs.particular.net/tutorials/nservicebus-101/

There is some mis-match between what this content is and what it claims to be.

The content is currently a single tutorial with several part. But some of the phrasing seems to imply it is online certification system. For examples. it reference "courses" and lessons, uses the phrasing "NServiceBus 101".

It comes across as the content is trying to appear to achieve more than it actually does

It is not a "online course" or a "university". There is

 * No certification
 * No Tests
 * no homework
 * no person reviewing your progress
 * no tracking of progress.
 * no videos

We should do a pass over the content ans change the phrasing to be more in keeping with what the content achieves.

 * remove the use of "course" 
 * change "lesson1" to "part1" ie "Lesson 1 - part 1"
 * remove the "NServiceBus 101" and replace it with "Introductory Tutorial". or simply "Messaging basics"

Happy if the tutorial eventually evolve into a more guided course in the future with tests/progress tracking etc. But that is a exponentially larger amount of work to maintain that we currently put into docs. If we decide to make that commitment in the future, we can re-brand the content at that time.

**Comment by weralabaj** [comment]
I think the name "academy" came up as an alternative to "bootcamp", which we didn't want to use, and then it just became how we think about this content :)

**Comment by kbaley** [comment]
I don't think much conscious thought went into the repercussions of the terminology but here's my take.

One of the secondary goals of the tutorial is to sell the platform for people just starting out. This is artistic license to make them feel like they're doing something meaningful and to stay engaged in the hope that they eventually become a paying customer. I don't think anyone will mistake it for an actual certifiable course.

**Comment by DavidBoike** [comment]
I think a lot is being read into a couple words that have little to do with their definitions.

* [course](http://www.merriam-webster.com/dictionary/course) - a number of lectures or other matter dealing witha  subject; also: a series of such courses constituting a curriculum
* [lesson](http://www.merriam-webster.com/dictionary/lesson) - a piece of instruction, a reading or exercise to be studied by a pupil, a division of a course or instruction

This seems to be pretty much in line with what we're trying to achieve.

We aren't using the words "academy" or "university" anywhere in docs.

As for the "101" concept, I think that's pretty much passed into everyday vernacular (i.e. [Homebrewing 101](http://www.northernbrewer.com/learn/homebrewing-101/), [Politics 101](http://uspolitics.about.com/od/usgovernment/u/politics_101_guide.htm), [JIRA 101](https://confluence.atlassian.com/jira064/jira-101-720412861.html), and even [Disney 101](http://www.visitflorida.com/en-us/articles/2009/october/1344-disney-101.html)) although that might be true only in the US. I like it because it implies, very succinctly, that it's a good place to start and has no prerequisites. It would also make an effective shorthand to denote prerequisites for further courses. (e.g. Azure 221 requires NServiceBus 101 + Azure 160 or whatever) But if the course numbering metaphor doesn't transfer internationally I'd be willing to change that to something else.

**Comment by weralabaj** [comment]
>  if the course numbering metaphor doesn't transfer internationally

Not sure about other places, but I'm very familiar with that phrase, for me it's synonym of "intro".

**Comment by SimonCropp** [comment]
The problem is not with 101 being "everyday vernacular". Just that in this case we dont need it. "Messaging Basics" is enough to convey what the tutorial is about. 

>  Azure 221 requires NServiceBus 101 + Azure 160 or whatever

Given we only have one tutorial ATM, we dont know how this will evolve in the future, it is too early to apply a numbering scheme.

This is applying "keep it simple" and Yagni to content. At the moment we have one tutorial with a few parts. Calling it anything other than that is unnecessary. Also calling it something else based on what it might evolve into is akin to making assuming on our ability to predict the future

> One of the secondary goals of the tutorial is to sell the platform for people just starting out. This is artistic license to make them feel like they're doing something meaningful and to stay engaged in the hope that they eventually become a paying customer. I don't think anyone will mistake it for an actual certifiable course.

"artistic license" at the risk of over promising and under delivering. People will just the content based on the content and what they learn. Not any kind of branding we attempt to apply to it.

re"course" and "lesson" atm the content throws those words about without any clear definition of what they mean. We should just go with "tutorial name and part number" this way we dont need to come up with a way to guide them down some cusomt vernacular that adds not value

**Comment by DavidBoike** [comment]
Disagree. Just focusing on more important edits to the course. I'm not at all OK with this.

**Comment by SimonCropp** [comment]
@DavidBoike so what of your concerns have not been addressed?

**Comment by SimonCropp** [comment]
another reason to avoid "courses" in the context of Particular/NserviceBus is that it conflicts with https://particular.net/courses-and-events

**Comment by DavidBoike** [comment]
Discussed with @brittking, @sergioc, and @kbaley.

My primary concern is that a "tutorial" with "parts" is the absolute most generic, tepid, watered-down, boring taxonomy possible, which will harm efforts to market and drive consumption of the content. Anyone can put up a tutorial on their blog. We're the only ones with the authority to publish a definitive course.

Meanwhile, most of the arguments against are specious at best. I highly doubt someone would get irate or sue because there are no tests or certifications, or get seriously confused between this and the ADSD course because of the use of the word course. (Also interesting, the ADSD course also does not have tests, homework, or certification.)

The only argument I can accept seriously is consistency, but the fact that the section is currently named tutorials is only because of [an earlier concession made in haste](https://github.com/Particular/DocsEngine/pull/220), so if we're going to consider a change, then changing `/tutorials/` to `/courses/`, or the possibility of having both, should be up for grabs as well. I will open a discussion issue to discuss branding consistency in OTE.

For now, this content is in testing by external users, and we would prefer not to rock the boat. Please hold off on any changes to the content until we're done with testing and deciding on branding.

**Comment by DavidBoike** [comment]
I lied, @sergioc says OTE isn't really interested in the branding aspects that much, so opened https://github.com/Particular/DeveloperEducation/issues/775.

**Comment by SimonCropp** [comment]
> Anyone can put up a tutorial on their blog. We're the only ones with the authority to publish a definitive course

Just as anyone can publish tutorials, anyone can publish course. Pluralsight does exactly that.

And you dont own the definitive guidance on anything on the web these days by virtue of being the company that sells it. you do so by having the best contant that is kept up to date.

i simply think we should name things in a way that most closely imparts to the consumer what that thing is. 

I would say "Guides" is also an appropriate term.

If you are concerned about naming something accurately will hurt marketing or branding, then we should not do the marketing or braiding until the content accurately reflects those aspirations. for example ATM i would not be happy with an announcement saying "particular now has online courses". 

I would prefer we did not overplay our hand on what we have delivered here. That was one for my original concerns with Academy. It sounds like we built something similar to  https://www.xamarin.com/university

**Comment by SimonCropp** [comment]
also re the overloaded "Courses" term inside particular. at one point the link to the current real "courses"  was linked in the header and footer of docs. based on how much priority that needs to be given in the future it might come back. this would clearly clash with any reference to "courses" inside the docs content or menu structure
