### ISSUE TITLE
Feedback: MS SQL Server Scripts - Sql Persistence

### ISSUE THREAD

**Issue by outofcoolnames** [Particular/docs.particular.net#2463]
Page: https://docs.particular.net/nservicebus/sql-persistence/sqlserver-scripts
Hi,
Our DBAs really despise nvarchars, would varchars suffice? I've scripted out a DB from SQL Server using DBGhost after changing to SQL Persistence and I'd need to justify why the columns need to be nvarchar. 
Thanks

**Comment by SimonCropp** [comment]
@outofcoolnames we went back and forth on this in discussions. 

We ended up on deciding to go with nvarchar for several reasons

 * sensitivity to cultures that have a complex character sets
 * saga type names can be Unicode
 * saga correlation property names can be Unicode
 * saga correlation property values can be Unicode
 * message correlation property names can be Unicode
 * message correlation property values can be Unicode
 * message types can be Unicode (since is seems weird to disallow unicode for saga types, saga property, and message properties but then allow it for message types)

disallowing Unicode seemed to rule out too many scenarios that should be supported

can you give some more details as to why your DBA despises nvarchars?

Also what is for a specific things you would prefer to be varchars ? or is it for everything?

**Comment by outofcoolnames** [comment]
Hi @SimonCropp ,
Thanks for the quick reply. Our DBA despises them as they are wasteful of data (using twice the amount of storage as varchar) and in our scenario (english speaking) it's just not needed.
### Specific columns I would argue over:
* TimeoutData.Headers being [nvarchar] (MAX). This is huge: [http://stackoverflow.com/questions/11131958/what-is-the-maximum-characters-for-the-nvarcharmax] considering the amount of data it will have to store. Nvarchar(4000) would still be huge
* TimeoutData.State being [varbinary] (MAX). Another huge one: [http://stackoverflow.com/questions/5723698/max-real-space-in-a-varbinarymax-in-sql-server]. To be honest, I'm not clear on what this is being used for but there are options out there for it e.g. varbinary(8000). Are there use cases for this that require the current column definition?
* OutboxData.MessageId being [nvarchar] (200). This looks to be storing guids, Should this be defined as uniqueidentifier?
* OutboxData.PersistenceVersion being [varchar] (23). In my db, all this contains is "1.0.0.0". Why was varchar(23) used?

### Extended properties
Have you considered added extended properties to the tables e.g. 
`EXEC sp_addextendedproperty @name=N'MS_Description', @value=N'The Id of the message' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Whatever_OutboxData', @level2type=N'COLUMN',@level2name=N'MessageId'
GO`
These extended properties would be useful additional information to provide, just a thought.

I'm sure there are great explanations associated with each of the questions I've raised.

**Comment by SimonCropp** [comment]
`(MAX)` is only huge if you store a huge amount of data in it. The links you quoted are the potential max size. if you do not think you will get close to them then that information does not apply.

We use `Max` since from a framework perspective we cant make any reasonable expectations of how big those fields are expected to be. And there seemed to be no downside to choosing `Max`

If you would still prefer to limit the MAX columns to a smaller value we should be able to add that as a config option. If you still think it is required could you add an issue here https://github.com/Particular/NServiceBus.Persistence.Sql/issues

for the non MAX columns you may want to look into [Unicode Compression](https://msdn.microsoft.com/en-us/library/ee240835.aspx)

> OutboxData.MessageId being [nvarchar] (200). This looks to be storing guids, Should this be defined as uniqueidentifier?

While the default is GUID it can be overridden to be an arbitrary string.

>OutboxData.PersistenceVersion being [varchar] (23). In my db, all this contains is "1.0.0.0". Why was varchar(23) used?

the max version number in .net is 65535.65535.65535.65535 hence 23 characters

> Extended properties

That is an awesome idea. can you raise an issue here https://github.com/Particular/NServiceBus.Persistence.Sql/issues

**Comment by outofcoolnames** [comment]
That's fair enough, If our DBAs still kick up a fuss, I may raise an issue.
I've raised that issue regarding the extended properties in [https://github.com/Particular/NServiceBus.Persistence.Sql/issues/28]()

**Comment by SimonCropp** [comment]
thanks for the feedback. and the issue raise

And yes if it becomes a larger issue with your DBA then raise an issue requesting it be configurable
