### ISSUE TITLE
NHibernate Persistence - Clarify what tables need to be created for deployment

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/docs.particular.net#2473]
Currently we have documentation here:
https://docs.particular.net/nservicebus/nhibernate/#generating-scripts-for-deployment

However, it does not sufficiently describe what tables are needed and left up to the user to turn on / off certain features in order to see what tables are used or might be needed. 

In certain environments, allowing the endpoints to automatically create the necessary tables is not an option. Having a concrete set of steps by which the user can generate the necessary schema for all persister tables will help alleviate any concerns that certain tables might not be scripted for deployment and can save deployment headaches.

---

Customer Reported Internal Case#: 00025081

**Comment by indualagarsamy** [comment]
ping @Particular/nhibernate-persistence-maintainers

**Comment by ericburcham-eprod** [comment]
These are remarks invited in email from the Particular support team.  I have replied to them via email, but am duplicating them here for posterity...

The description is insufficient in general, though you might be best served to use two issues:
1.	For documentation.
2.	For an NServiceBus.NHibernate persister feature.

The fundamental problem I'm trying to address is not to get a list of tables, but to generate the tables.  A list does me absolutely no good if I don't know what columns, data types, keys, indexes, etc… are expected.  Frankly, I would suggest you post the necessary SQL in the documentation and allow the user to copy/paste/edit by hand as necessary.  You might point out that the default schema of 'dbo' (or whatever it is) can be changed in a comment.

OK, on to the text:

I think you left out a few words:
"However, it does [not] sufficiently describe what tables are needed and left up to the user to turn on / off certain features in order to see what tables are used or might be needed."

In certain environments, [allowing] the endpoints to automatically create the necessary tables is not an option.


Here is an edit that makes the problem more clear, though I leave it up to you to decide how to organize the information.

Yours:
Having a concrete [list of the tables used in the persistence] will help alleviate any concerns that certain tables might not be scripted for deployment and can save deployment headaches.

Mine:
Having a concrete [set of steps by which the user can generate the necessary schema for all persistence tables] will help alleviate any concerns that certain tables might not be scripted for deployment and can save deployment headaches.

**Comment by indualagarsamy** [comment]
@ericburcham-eprod  - I have updated the issue description. 
Yes, my goal for raising the issue in docs is to have the necessary SQL also posted to help create the tables. I should have clarified that much better! Thanks again.

**Comment by MarcinHoppe** [comment]
We have discussed this issue at length within @Particular/nhibernate-persistence-maintainers team, and we concluded that there is no way for us to provide reliable documentation here, given how flexible NHibernate can be when it comes to mapping, especially for sagas.

Given that we have [SQL Persistence](https://docs.particular.net/nservicebus/sql-persistence/) where DDL generation is a first-class feature, we decided to close this issue.

**Comment by ericburcham-eprod** [comment]
As a consumer of the NHibernate persister I have to disagree.  Referring me to the SQL Persistence when I have another flavor in production is completely inadequate, and feels very out of character given the usual quality of solutions I get from your team.  The DDL for the SQL persister is not the same as that for the NHibernate persister.  They are very different features, and the NHibernate version deserves to be a first-class citizen as well, or to go the way of the Dodo Bird.

As a suggestion, you could provide reliable documentation for all the features that are not so flexible.

Guys, listen.  We have an entire suite of applications (30 or something) and standing it all up locally just to generate schema for tables is, well, a real pain in the arse.  Is that your fault?  Nope.  Certainly not.  Could you help out a lot anyway?  Yep.  Sure could.

I'd tackle it in two parts:

1.        Here is the stuff that doesn't change.  Here is the DDL for that stuff.  If you want a different schema, do a find/replace for [this] with [that] in your favorite editor.  Merry Christmas!

2.       Here is the stuff we can't easily give you scripts for.  Here is why.  Here is, abstractly but specifically, how to get the scripts anyway, since we all know that your favorite app SHOULD NOT have DDL permissions in your production environment, so say almost every DBA in the world.  Good luck.

Just my $0.02, but it is a pretty strong opinion, having been through all this already.

**Comment by MarcinHoppe** [comment]
@ericburcham-eprod Thanks for your comments, we appreciate them a lot. We wholeheartedly agree that the application should never ever have privileges to execute DDL statements in production, or even staging.

We are looking at providing better documentation and guidance for our customers using the NHibernate persistence, including generation of DDL scripts and migration of database objects managed by NServiceBus between databases and environments.

Stay tuned.

**Comment by MarcinHoppe** [comment]
#2677 has been created to address some of the pain.
