### ISSUE TITLE
Feedback: Steps, Stages and Connectors - NServiceBus

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2480]
Page: https://docs.particular.net/nservicebus/pipeline/steps-stages-connectors

Section "Other Pipeline Stages":
- "Transport Receive" stage is listed in both this section and in the previous section "Incoming Pipeline Stages".
- A [code search on GitHub for `IBatchDispatch`](https://github.com/Particular/NServiceBus/search?utf8=%E2%9C%93&q=IBatchDispatch&type=Code) yielded no result.

**Comment by weralabaj** [comment]
ping @Particular/nservicebus-maintainers does that article need an update?

**Comment by timbussmann** [comment]
seems like it does need some update. Thanks for raising this @Niklas-Peter 👍 

as the transport-receive stage is already documented, this can be removed which leaves the `IBatchDispatchContext` (instead of `IBatchDispatch`) left. Seems like this should be moved to the outgoing pipelines instead so we can remove the "others" section entirely. Thoughts?

**Comment by weralabaj** [comment]
@timbussmann I think we can remove the "others" section. Question though, is replacing behaviours in IBatchDispatchContext worse idea than replacing any other stage? Should we make a note about it?

**Comment by timbussmann** [comment]
replacing behaviors is a bad idea in general, no need to differentiate imho. Will raise a PR.

**Comment by timbussmann** [comment]
removed the "other pipeline stages" section in #2529 and moved the mentioned stages to their corresponding incoming/outgoing stages section.

Thanks again for the feedback @Niklas-Peter 👍
