### ISSUE TITLE
Feedback: 'Saga Concurrency'

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2534]
Feedback for 'Saga Concurrency' https://docs.particular.net/nservicebus/sagas/concurrency

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/sagas/concurrency.md

ping @Particular/nservicebus-maintainers

The documentation only mentions NHibernate and RavenDB concerning concurrency. What is about SQL Persistence?

Why this question?
I use a saga for aggregating multiple messages in one output message. Using InMemoryPersistence or NHibernatePersistence it seems to work. 

However, SqlPersistence fails pretty often if the concurrency limit is not set to 1: I would expect the code below to result in 2 outgoing messages:

1. Message 1, 2, 3
2. Message 4

Instead, with SqlPersistence it repeatedly is like that:

1. Message 1, 2, 3
2. Mesesage 1, 2, 4 

I think messages 3 and 4 are processed in parallel and the saga concludes that both of them were the 3rd message in the aggregate, so that it sends the output message twice. 

Changing the transaction isolation level does not affect the behavior.

I do not know what its semantics are, but the column "concurrency" in the SqlPersistence table is always 1.

Pseudo code:
Saga:

	Handle(message)
	{
	   Aggregate(message); // Merge previous saga state with the received message
	   sagaState.NumMessages++;   
	   if(sagaState.NumMessages >= 3)
	   {
		  SendOutputMessage();
		  MarkAsComplete();
	   } 
	}

Sender

	for(var i = 0; i < 4; i++)	
	{
		SendMessage(); // all messages have the same saga correlation ID value
	}

In ServicInsight:
![2017-03-09_134054](https://cloud.githubusercontent.com/assets/1985634/23750992/be24b3fc-04cf-11e7-8833-7a53318209a7.png)

**Comment by indualagarsamy** [comment]
@Particular/sqlpersistence-maintainers - can you evaluate this to see if it's a bug in the persistence?

**Comment by indualagarsamy** [comment]
@Niklas-Peter - Thank you for your feedback. We will evaluate to see if this is a bug in the SqlPersistence. If so, we will raise an issue in the SqlPersistence repository here: https://github.com/particular/nservicebus.persistence.sql

As far as the missing documentation, we will also review it and see what relevant section needs to be added.

**Comment by SimonCropp** [comment]
@SzymonPobiega given u wrote most of the concurrency code can u have a look at this one?

**Comment by SzymonPobiega** [comment]
@SimonCropp yeah, I'll take care of this.

**Comment by SzymonPobiega** [comment]
@Niklas-Peter I've tried to reproduce it but failed. Here a [gist](https://gist.github.com/SzymonPobiega/59775a4f5615d1864b3f7416734c365f) with my code. Please check if it does the same as yours.

The behavior I observe is that a message is sent out after three incoming messages. The forth message initiates creation of another saga instance with same correlation ID. Depending on concurrency settings, the forth message can sometimes fail in the first attempt due to conflict with the `DELETE` caused by `MarkAsComplete` in the previous message.

Also, I could verify in the debugger that the concurrency column is indeed being incremented: it is set to 1 after the first message and then set to 2 after the second one. The third messages causes the delete so the ultimate result is always 1 as the forth message creates a saga again (with same correlation id).

**Comment by Niklas-Peter** [comment]
@SzymonPobiega It looks similar to what I did. However, I do not use SqlPersistence anymore. Sorry, but I do not have time to do further research about why it did not work for me.
