### ISSUE TITLE
Feedback: 'Containers'

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2545]
Feedback for 'Containers' https://docs.particular.net/nservicebus/containers/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/containers/index.md

ping @Particular/nservicebus-maintainers

> IEndpointInstance needs to be registered to be properly resolved.

`RegisterComponents` is only available in `EndpointConfiguration`. Is the only possibility to register objects after the endpoint instance was started using the container specific API, e.g., `kernel.Bind<IEndpointInstance, IMessageSession>.ToConstant(endpointInstance)` in Ninject?

I need `IMessageSession` in a custom class (neither a handler nor a saga) that sends a message.

**Comment by indualagarsamy** [comment]
@Niklas-Peter - Rather than have IMessageSession injected in your custom class, it should be passed in from the same handler or the endpoint instance. Can you please explain your use case you're trying to achieve? 
More on this: https://docs.particular.net/nservicebus/upgrades/5to6/moving-away-from-ibus#dependency-injection

cc / @Particular/container-maintainers

**Comment by Niklas-Peter** [comment]
Thanks for your reply.

Is it a goal of NServiceBus to abstract the containers or do you intend to use the container-specific API anyway? If the latter is true, I wonder why there are independent methods like EndpointConfiguration.ConfigureComponent(), i.e., why can you do container-independent registrations at configuration time, but not at the endpoint runtime?     
Maybe I got something wrong.

    class MyClassOutsideHandler : IMyInterface
    {
        private readonly IMessageSession _session;

        public MyClassOutsideHandler(IMessageSession session)
        {
            _session = session;
        }

        public void MyMethod()
        {
            _session.Send(new MyMessage());
        }
    }

    internal interface IMyInterface
    {
        void MyMethod();
    }

    internal class MyMessage : IMessage
    {
    }

    static async Task MainAsync() // Composition root
    {
        var config = new EndpointConfiguration("MyEndpoint");

        var kernel = new StandardKernel();
        config.UseContainer<NinjectBuilder>(
            customizations =>
            {
                customizations.ExistingKernel(kernel);
            });

        var endpointInstance = await Endpoint.Start(config).ConfigureAwait(false);

        // Is this possible in a container-independent way?
        kernel.Bind<IEndpointInstance, IMessageSession>().ToConstant(endpointInstance);

        kernel.Get<IMyInterface>();
    }

**Comment by mikeminutillo** [comment]
>  why can you do container-independent registrations at configuration time, but not at the endpoint runtime?

Not all of the containers that can be used with NServiceBus allow updating the contents of the container once it has been built. The API provided allows you to contribute to the configuration of the container before the container is constructed (during the endpoint start) but not afterwards. 

If you want to do this in a container independent way, you can do something like this:

```csharp
static async Task MainAsync()
{
  var config = new EndpointConfiguration("MyEndpoint");

  config.RegisterComponents(
    cc => cc.ConfigureComponent(b => MessageSessionStash.Instance, DependencyLifecycle.InstancePerCall)
  );

  MessageSessionStash.Instance = await Endpoint.Start(config).ConfigureAwait(false);
}

static class MessageSessionStash
{
  public static IMessageSession Instance;
}
```

Every attempt to resolve `IMessageSession` will call the func and return the value stashed in the static class.

If you do this you need to ensure that you aren't accessing the `IMessageSession` in any class that is going to be resolved before the return of `Endpoint.Start` otherwise you will resolve a `null` instance.

**Comment by Niklas-Peter** [comment]
Thanks.
