### ISSUE TITLE
Feedback: 'Message Headers' - CorrelationId when sending from a saga

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/docs.particular.net#2547]
Feedback for 'Message Headers' https://docs.particular.net/nservicebus/messaging/headers

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/headers.md

ping @Particular/nservicebus-maintainers

> Message correlation connects request messages with their corresponding response messages. The Correlation Id of the response message is a Message Id of its corresponding request message.

When sending a request from within a saga and trying to receive the response in a handler outside the saga (special case, I can not receive the response in the saga, because I have to complete the saga after sending the request), this is obviously not true. The `CorrelationId` of the response is not set to the `MessageId` of the request, but to the message ID of the message initiating the saga.

The `RelatedTo` header contains the request's message ID. However, I do not want my response handler have to know, whether the corresponding request was sent from a saga or not. 

Is there a reason to not always use `RelatedTo` in a response handler for request-response correlation?

**Comment by mikeminutillo** [comment]
Hi @Niklas-Peter 

Once a `CorrelationId` has been set for a conversation, it is sticky and is carried forward to every new message in the conversation. 

Your intuition to rely on `RelatedTo` for this is correct. `RelatedTo` will always be the `MessageId` of the message that was being handled when this message was sent.

**Comment by Niklas-Peter** [comment]
@mikeminutillo 
> Once a CorrelationId has been set for a conversation, it is sticky and is carried forward to every new message in the conversation.

Why do we need an additional `NServiceBus.ConversationId` then?

**Comment by mikeminutillo** [comment]
@Niklas-Peter in previous versions of NServiceBus it was possible to switch to a different `CorrelationId` within the same `ConversationId`. In Version 6 and above this is still possible (by manually setting a `CorrelationId` on an outgoing message) but I'm not sure why you'd want to do it. 

The `CorrelationId` header was originally added to enable synchronous Callbacks. In NServiceBus Version 6 and above, this type of interaction can only be initiated by the very first message in a conversation and any given conversation is unlikely to have multiple `CorrelationId`s.

I believe the `RelatedTo` header was added afterwards (probably to enable the Message Flow Diagram in ServiceInsight). 

We had a brief discussion internally about renaming some of these headers but in order to allow backwards compatibility we need to keep them as they are.

We will review the documentation and see what we can do to make it clearer.

**Comment by SimonCropp** [comment]
@mikeminutillo is this still on your todo list?

**Comment by weralabaj** [comment]
ping @mikeminutillo should we find somebody to take over?

**Comment by mikeminutillo** [comment]
@weralabaj yes please. Sorry about dropping the ball on this.

**Comment by mikeminutillo** [comment]
This has been updated. Sorry it took so long. 

@Niklas-Peter if you get a chance, please take a look and see if the differences between these headers is clearer.
