### ISSUE TITLE
Feedback: 'Client side Callbacks'

### ISSUE THREAD

**Issue by cremor** [Particular/docs.particular.net#2563]
Feedback for 'Client side Callbacks' https://docs.particular.net/nservicebus/messaging/callbacks

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/callbacks.md

ping @Particular/nservicebus-maintainers 

I think this paragraph should be improved:

> The endpoint queue name will include the specified suffix. When upgrading from lower versions the original input queue (without a suffix) will still exist, and the additional queue with the suffix will be created.

I interpreted the "upgrading from lower versions" as "upgrading from NServiceBus versions 5 and below". And then I interpreted the "will still exist" part as "the new version won't create the queue without a suffix". But this doesn't seem correct because if I create a new endpoint with NServiceBus 6 on which `MakeInstanceUniquelyAddressable` was called, both types of queues, with and without a suffix, are created. At least with MSMQ, maybe this is dependend on the transport?

**Comment by dvdstelt** [comment]
@cremor I created a PR that should clarify it.

There should be 2 queues, one that is shared by consumers, the other that is consumer (aka instance) specific. In MSMQ there's not really a difference between the two, but since the feature(s) is not transport specific, there are still two queues. With a brokered transport, there's 1 shared queue for all consumers and a specific queue per instance.
