### ISSUE TITLE
Restore cluster doco

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#2611]
It seems it got removed https://github.com/Particular/docs.particular.net/issues/2186 but this is frequently requested.

I would be in favor of restoring and even updating this documentation.

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers given you would own this and be required to keep it up to date can u chime in

**Comment by bording** [comment]
@SimonCropp We've just formed @Particular/msmq-transport-maintainers, so they would be the owners now.

**Comment by SimonCropp** [comment]
For context I spent over 4 months trying to get this page updated https://github.com/Particular/docs.particular.net/issues/2186

**Comment by indualagarsamy** [comment]
I am against restoring the previous documentation as is because setting up a MSMQ cluster is outside the scope of NServiceBus Documentation. It might change based on Operating System. What you need to do in Server 2008 RC2 might be different in Server 2012 and in the future.  From a support perspective, if someone wants to know how to setup a MSMQ cluster refer them to the MS article, https://blogs.msdn.microsoft.com/biztalknotes/2013/03/20/how-to-install-and-cluster-msmq-on-windows-server-2012/

From the perspective of NServiceBus, what I think needs to be addressed is:
- If you setup a cluster (following the MS directions), is there anything else that needs to be done, for example, on the endpoint that's trying to send messages to the cluster, are there are any differences?

**Comment by SimonCropp** [comment]
@ramonsmits dont think this needs an issue. submit a PR to illustrate the type of content you see would still be valuable given the distributor is deprecated and that wont overlap with content that MS should own
