### ISSUE TITLE
Feedback: 'NHibernate Persistence'

### ISSUE THREAD

**Issue by cremor** [Particular/docs.particular.net#2711]
Feedback for 'NHibernate Persistence' https://docs.particular.net/nservicebus/nhibernate/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/nhibernate/index.md

ping @Particular/nhibernate-persistence-maintainers 

About this note in the section "Subscription caching":

> Publishing is performed on stale data. This is only advised in high volume environments where latency can be a potential issue.

Is this really true? I checked the [implementation](https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/Subscriptions/CachedSubscriptionPersister.cs) and for me this seems like to invalidate the cache each time a subscription is added or removed. So the persistence should never return stale data, right?

Or was this just written as a precaution in case the persistence switches to a different implementation some time in the future?

**Comment by weralabaj** [comment]
@Particular/nhibernate-persistence-maintainers

**Comment by DavidBoike** [comment]
@cremor Yes, if a subscribe/unsubscribe request is received, then the database will be updated and the cached data will be dropped so that the next publish will get the updated data.

However, consider a scaled-out scenario with multiple endpoint instances. If the subscription request gets routed to Instance1, the next publish on Instance1 will use the new values, but the next publish on Instance2 may publish with values that are stale.

**Comment by cremor** [comment]
Ok, that makes sense. Thanks for the explanation.

If you don't want to mention that in the documenation I'd be fine with it. Otherwise I suggest a simple change like "Publishing might be performed on stale data in a scaled-out scenario."

**Comment by DavidBoike** [comment]
There are other edge cases too. An administrator could manually update the database. It's probably better to be more general.
