### ISSUE TITLE
Feedback: 'Competing Consumers And Sender-Side Distribution'

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#2733]
Feedback for 'Competing Consumers And Sender-Side Distribution' https://docs.particular.net/samples/scaleout/senderside/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/scaleout/senderside/sample.md

ping @Particular/nservicebus-maintainers 

Should we make a clear note that sender side distribution applies, when used to scale out, applies to MSMQ only.  Because reading this:

> Sometimes a single endpoint for handling messages is not enough so there is a need to scale out. The following sample demonstrates how to scale out existing message processing either by using competing consumers approach or by distributing messages by the sender.

It seems that it applies to all transportation with no distinctions.
Also the following note in the [Competing Consumers](https://docs.particular.net/samples/scaleout/senderside/#running-the-code-competing-consumers) section

> The competing consumers scale out approach only works with all scaled out receivers running on the same machine.

Seems to imply that on all transports endpoints should live on the same machine.

**Comment by timbussmann** [comment]
the instance mapping file closely belongs to MSMQ and will even be moved out of the core once MSMQ is extracted, so yes this sample belongs to MSMQ.

**Comment by janovesk** [comment]
You never "scale out" MSMQ with `competing consumers`, so saying this sample should be MSMQ specific  when it includes a `competing consumers` comparison is weird. If it's ment to be MSMQ specific, it should, if anything, compare `the distributor` to `sender-side distribution`.

Either we need to:

1. Keep the sample and say `sender-side distribution` is transport agnostic. Then this sample makes sense, because `competing consumers` vs `sender-side distribution` is a real choice.
or
2. Say `sender-side distribution` as a feature is MSMQ specific. That means we change the sample to be an example of `sender-side distribution` only and remove everything related to `competing consumers`.

My money is on 2

Thoughts @timbussmann and @mauroservienti ?

**Comment by timbussmann** [comment]
> Keep the sample and say sender-side distribution is transport agnostic

as only MSMQ offers a ssd API, I'd say that's not really true (unless you fiddle with the low level routing APIs).

👍 for option 2

**Comment by janovesk** [comment]
Okay, I'll rewrite for 2.
