### ISSUE TITLE
Feedback: 'Introduction to NServiceBus: Retrying errors'

### ISSUE THREAD

**Issue by zagnut999** [Particular/docs.particular.net#2738]
Feedback for 'Introduction to NServiceBus: Retrying errors' https://docs.particular.net/tutorials/intro-to-nservicebus/5-retrying-errors/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/tutorials/intro-to-nservicebus/5-retrying-errors/tutorial.md

```Replay a message```
The screenshots and instructions are out of date.  There is no "View Messages" link any longer, for instance.

**Comment by mikeminutillo** [comment]
Thanks @zagnut999 

I will run through the sample and retake the screenshots.

**Comment by DavidBoike** [comment]
@zagnut999 Sorry for the delay, but that page has now been updated. Note that you may have to do a force refresh (Shift+F5) to get the images to update, as we cache the docs site fairly aggressively.

Please note that this is only a temporary fix. We're working on changing the 5-lesson introductory tutorial to use the new Learning Transport, which is much easier to get started with and doesn't have any MSMQ dependency. When that happens, the "message replay" sections will get split out into a separate tutorial specifically about message replay, since you have to use a real message transport to take advantage of the platform features.

In any case, when that split is complete we may consider expanding the coverage of the message replay feature in ServicePulse with more screenshots and description.
