### ISSUE TITLE
Feedback: 'Manipulate Pipeline with Behaviors'

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#3293]
Feedback for 'Manipulate Pipeline with Behaviors' https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors

We mention that the custom behavior can be used to replace an existing behavior, the method expects to specify a step id. However, it's never explained how I can find the existing step id (are those fixed or can change? any other way to find out than debug?).

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/pipeline/manipulate-with-behaviors.md

ping @Particular/nservicebus-maintainers

**Comment by andreasohlund** [comment]
You are correct, we currently doesn't provide a list of id's and we don't really guarantee them to be stable since we have no tests that verifies.

@Particular/nservicebus-maintainers the whole API feels like a backdoor and I wonder if we should consider to remove it similarly to how we [contemplate removing support for removing/replacing stage connectors](https://github.com/Particular/NServiceBus/issues/3642)?

**Comment by andreasohlund** [comment]
As a first step we could remove all doco for remove/replace?

@SimonCropp I know that the [multi deserializer sample](https://github.com/Particular/docs.particular.net/blob/052de9bd559446988f0b106dc52d2d90987dbedd/samples/pipeline/multi-serializer/Core_6/Shared/MultiSerializerFeature.cs) depends on this, do you remember other samples on top of your head?

**Comment by SimonCropp** [comment]
Not sure of other samples, would need to search

Also note this is not just about remove replace. The insert before and after api has the same problem

**Comment by andreasohlund** [comment]
>The insert before and after API has the same problem

Very good point.

So there seems to be 2 issues:

1. We have a public supported API that relies in magic strings for which we have no list/doco
2. The above strings are not verified as a public API so we could break it by mistake (not sure if this is a real issue since I'm pretty sure our PR reviews would catch it)

How do we proceed?

**Comment by weralabaj** [comment]
@andreasohlund but I need to replace the step to get custom conversation ids in the "integration-like" scenario, so if you remove that feature now I'll have no way to get it done (or I'm at least not sure how to do it otherwise yet, without replacing original behavior).

**Comment by weralabaj** [comment]
I was thinking about documenting how you can find that in code, but that will be a PITA for various versions. Achievable and if we assume it'll be rarely used, then may work, though?

**Comment by andreasohlund** [comment]
>I was thinking about documenting how you can find that in code, but that will be a PITA for various versions. Achievable and if we assume it'll be rarely used, then may work, though?

Right now we have no better way

**Comment by weralabaj** [comment]
I'll document that then as discussed with @andreasohlund on a call, and submit a PR

**Comment by weralabaj** [comment]
Fixes in https://github.com/Particular/docs.particular.net/commit/faed80c0125118c18930ff898ff89ce0adcfe987
