### ISSUE TITLE
Feedback: 'Upgrade Version 6 to 7'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3365]
Feedback for 'Upgrade Version 6 to 7' https://docs.particular.net/nservicebus/upgrades/6to7/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/upgrades/6to7/index.md

@msmq-transport-maintainers why point to the location of the script in the nuget cache https://docs.particular.net/nservicebus/upgrades/6to7/#msmq-provision-of-powershell-scripts. the usage scenario is those are outputted as part of the build.  isnt the location in the nuget cache is an implementation detail

**Comment by janovesk** [comment]
We are looking into this @SimonCropp

**Comment by indualagarsamy** [comment]
@SimonCropp - Since we don't have a MSBuild, the scripts are being packaged as part of the Nuget folder. I thought it might be easier to provide the location since I had to hunt to find the location of the nuget folder when I was looking for it. Do you think the additional info is gonna hurt or do you think it should be part of the build for the endpoint?  

@andreasohlund mentioned that it might be a good idea to try and have a uniform location or a consistent approach for all transports or persistences that output deployment scripts.

**Comment by SimonCropp** [comment]
I think it would be better for the scripts to be part of the nugets content files? https://docs.microsoft.com/en-us/nuget/schema/nuspec#including-content-files

**Comment by andreasohlund** [comment]
That still doesn't mean that they get dumped under solution folder right? (for that we would need a msbuild task?)

**Comment by SimonCropp** [comment]
> for that we would need a msbuild task

It can do it in a pure msbuild file. no custom target required

**Comment by andreasohlund** [comment]
That sounds good to me, so we should dump them in bin/debug like sqlp does it? (https://docs.particular.net/persistence/sql/installer-workflow#contrasting-workflows-development-workflow)

**Comment by janovesk** [comment]
Scripts are now dumped to the build output. Closing this.
