### ISSUE TITLE
Feedback: 'Message Headers': missing CorrId  doco

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3371]
Feedback for 'Message Headers' https://docs.particular.net/nservicebus/messaging/headers

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/headers.md

ping @Particular/nservicebus-maintainers

i cant see any doco for `CorrId`?

**Comment by andreasohlund** [comment]
If I remember correctly `CorrId` was a msmq specific header

https://github.com/Particular/NServiceBus.Transport.Msmq/blob/develop/src/NServiceBus.Transport.Msmq/MsmqUtilities.cs#L155

@Particular/msmq-transport-maintainers do you remember?

**Comment by andreasohlund** [comment]
Pretty sure that header is only needed for v3 and since we're about to remove doco, wire compat tests etc for v3 should we hold off with documenting?

**Comment by janovesk** [comment]
I think it is even older. V3 only used to to be backwards compat to pre-v3 as far as I remember.

**Comment by weralabaj** [comment]
So the conclusion is we're not documenting because it's only used in versions that are not currently supported?

If we're using it in versions above v3, even if only for backwards-compatibility, then we should document though. People may see that header when peeking at messages and wonder what's that about.
