### ISSUE TITLE
Feedback: 'Amazon SQS Transport'

### ISSUE THREAD

**Issue by timbussmann** [Particular/docs.particular.net#3392]
Feedback for 'Amazon SQS Transport' https://docs.particular.net/transports/sqs/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/sqs/index.md

ping @Particular/aws-maintainers

The page does mention the `Region` and `S3BucketForLargeMessages` extension methods (mentioned in the configs page as well) which seem to be obsolete (and replaced by a more complicated API?).

Also, is there a way to pass all these settings just via connection string or are these extension methods methods mandatory?

**Comment by timbussmann** [comment]
another observation: why does the `S3` config option return a S3 settings which only contains a `ClientFactory` method, which is also present on the transport settings already?

**Comment by danielmarbach** [comment]
Thanks @timbussmann for your feedback. We definitely did overlook the mentioning of the region when we introduced the new API. @Particular/aws-maintainers will address this. From my point of view the snippet is a bit misplaced there anyway and can be removed and potentially be replaced with a link to the configuration page. 

Regarding the more complex API. When SQS transport adapter was first written it was written in a time when we thought it is a good idea to wrap as many settings as possible. With the rise of new transports over time we started to realize that for complex settings it is better to expose the SDK types directly. We also good valuable insight from people using it in production such as https://github.com/Particular/NServiceBus.AmazonSQS/issues/129 which highlighted that even more. The decision was to introduce client factories for each AWS SDK type that is used inside the transport. Which is the SQS client and the S3 client. Everything directly transport related was put on the level of the transport. S3 related settings are now grouped together in the S3 related part of the transport config API. The API decision for S3 was the following: Mandatory settings belong directly into the S3 method while optional settings belong to the extension part of `S3Settings`. 

Since v4 the transport always uses the default constructor of the SDK types which means the default conventions applied by the SDK are directly applied for things like credentials, region etc. We tried to outline that in the doco with statements like

> By default the endpoint uses the SDK to retrieve the default AWS region from the AWS_DEFAULT_REGION environment variable.

> By default the endpoint uses the SDK to retrieve AWS credentials. The AWS SDK permits a large number of transparent methods for configuring the credentials as outlined in the [.NET SDK guidelines](http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html).

This leads to fewer settings that are required that deviate from the way the SDK natively behaves which we hope is big win for all of us.

Could it be that it is misleading to have settings of Region as marked as mandatory? We thought it is helpful because you need the Environment ENV `AWS_DEFAULT_REGION`. 

Or should we improve the upgrade guide https://docs.particular.net/transports/upgrades/amazonsqs-3to4?

**Comment by timbussmann** [comment]
>  We thought it is helpful because you need the Environment ENV AWS_DEFAULT_REGION.

I wasn't aware that there is the ability to specify those settings in the env vars. Althought tbh, on my development machine I don't like to "spam" my env variables with settings like that just to run a sample (especially since the default region doesn't seem to be security critical and therefore could easily be managed by code).

**Comment by weralabaj** [comment]
@timbussmann @danielmarbach Do you have some agreement on how to address the feedback? Any way I could help?

**Comment by danielmarbach** [comment]
@Particular/aws-maintainers We cannot come up with a sensible default region in the code. Since the default approach in the SDK is to rely on ENV variables I propose to close this as won't fix.
