### ISSUE TITLE
Feedback: 'Step by Step Sample'

### ISSUE THREAD

**Issue by robvon** [Particular/docs.particular.net#3394]
Feedback for 'Step by Step Sample' https://docs.particular.net/samples/step-by-step/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/step-by-step/sample.md

ping @Particular/nservicebus-maintainers

Main routine as an async Task can not be directly started as a console app.  Just add "MainAsync().GetAwaiter().GetResult();" or whatever.

Regards

Rob

**Comment by weralabaj** [comment]
ping @DavidBoike

**Comment by DavidBoike** [comment]
Hi @robvon,

`static async Task Main()` actually works just fine when you're using C# 7.1. That's one reason we upgraded all our samples to use C# 7.1 rather than Visual Studio's default behavior of using 7.0, so that we can remove the boilerplate and focus on the meat of what's going on in the sample.

Here's a blog post on [3 ways to enable C# 7.1 features](https://www.meziantou.net/2017/08/24/3-ways-to-enable-c-7-1-features) in your own projects.

**Comment by SimonCropp** [comment]
@robvdlv and a bit more information on async main https://blogs.msdn.microsoft.com/mazhou/2017/05/30/c-7-series-part-2-async-main/

**Comment by robvdlv** [comment]
@robvon, @SimonCropp intended to mention you instead of me ;-)

**Comment by SimonCropp** [comment]
@robvdlv doh. Thanks
