### ISSUE TITLE
Does installing NServiceBus.DTC require a reboot?

### ISSUE THREAD

**Issue by Powellellogram** [Particular/docs.particular.net#3428]
If I were to either use Install-NServiceBusDTC or manually edit the NetworkDtcAccess, NetworkDtcAccessOutbound, NetworkDtcAccessTransactions and XaTransactions registry keys, would this require a reboot to work? Or is there a Service I can simply restart?

**Comment by dvdstelt** [comment]
@Powellellogram Worst case scenario is that the `Distributed Transaction Coordinator` service needs a restart. `Install-NServiceBusDTC` will do this automatically.
The service can be found under Windows services:

![image](https://user-images.githubusercontent.com/1257410/32716767-83ebfd7a-c857-11e7-9785-01ea26ca34b4.png)

I'd also advise to change DTC settings using "Component Services" rather than the registry. Right-click "Local DTC" to change properties.

![image](https://user-images.githubusercontent.com/1257410/32716845-cac90580-c857-11e7-8eb8-1eb5934670c9.png)

On another note, we are used to use GitHub primarily for issues related to the repository. So this `docs.particular.net` repository would contain issues around documentation. Were you missing information around this in our documentation? The MSDTC related part of your question is probably found on MSDN, but perhaps we could provide a link to it?

If you'd like to discuss NServiceBus in general or anything related to it, we also have our community platform at https://discuss.particular.net/
You're completely free to raise just about anything there. Others from the community might respond as well and provide insightfull information. Perhaps you'd like to have a look at it. It's fairly new, that's why there's not much historical data. That would be at our (older and closed) [Google Groups](https://groups.google.com/forum/#!forum/particularsoftware).

**Comment by Powellellogram** [comment]
Apologies for asking in the wrong place, but thank you for your detailed reply. I couldn't find any specific information on whether or not the install would require a server reboot or not so ended up asking here. Several of my installs failed due to out of date .Net so I'll have to install some features separately during business hours.

**Comment by dvdstelt** [comment]
@Powellellogram It wasn't my intention to set GH away as the wrong place to ask questions, I merely wanted to ask if you thought doco was missing and also point you towards other possibilities! :-)

Let me know if you succeed in getting it to work or if you need any help.

**Comment by weralabaj** [comment]
@Powellellogram Seems like this thing is not really NServiceBus specific. If you think it still would be helpful to add a note somewhere in our documentation, please, reopen the issue and suggest a specific place where you looked for it when troubleshooting. I think it's likely other people would have a similar approach to yours :)
