### ISSUE TITLE
Feedback: 'Service Fabric Hosting'

### ISSUE THREAD

**Issue by martinkullich** [Particular/docs.particular.net#3561]
Feedback for 'Service Fabric Hosting' https://docs.particular.net/nservicebus/hosting/service-fabric-hosting/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/service-fabric-hosting/index.md

I think it is probably worth pointing out that Send Only endpoints in service fabric would not start the endpoint in a communication listener.  If you are sending a command from ASPNET, for example, then you’d start the endpoint in the Startup class just as you would outside of Service Fabric.

**Comment by danielmarbach** [comment]
@martinkullich thanks for the feedback. Do you think it would be worth adding another snippet or is it enough to mention send-only endpoints like you described? The problem I see is that it depends in what context the endpoint is used. If the endpoint is used inside ASPNET hosted inside service fabric then you'd probably want to use the startup class since the service fabric middleware adds the kestrel listener that then invokes the OWIN pipeline. In such a case the normal ASPNET hosting guidelines apply. That being said it is perfectly valid though even then host the endpoint inside a communication listener since you can register multiple communication listeners and then pass the endpoint owned by that listener to the kestrel listener service registration endpoints. Furthermore one can also envision a scenario where a stateless or stateful service only needs to send or publish events but never receive. In such a case the send-only endpoint would also be hosted inside a communication listener. I'm not sure how detailed our guidance should be there because it could become a bit confusing. Do you have any suggestions?

**Comment by martinkullich** [comment]
I'm not sure I know enough Service Fabric to advise.  It seems to me that currently most people using NServiceBus with Service Fabric for the first time are likely to be new to Service Fabric rather than new to NServiceBus - this is certainly my experience.  
Setting up my Service Fabric application for the first time, I created a service with a Kestrel stateless service instance listener.  Then I thought I'll have my ASPNET code running in Kestrel send a command using NServiceBus.  If I hadn't seen this documentation I would have started my endpoint in the usual ASPNET way.  But I did see the Service Fabric hosting guidance and it got me thinking that I would need to create  two service instance listeners - one for Kestrel and one for NServiceBus.  As far as I know (and I could be wrong) there is no way to control the startup order of service instance listeners.  I would have needed a way to inject the NServiceBus endpoint into the Kestrel hosted code.  This can only be done once the NServiceBus endpoint has started.  So when the first HTTP requests come in, there may not be an IMessageSession object available yet - or did I miss something?
I do use the way described in this documentation to create SF services that only contain NServiceBus, so that is very useful.  I think the ways of hosting should at least be pointed out.

**Comment by danielmarbach** [comment]
I give this a closer look today. Thanks for your feedback @martinkullich

**Comment by martinkullich** [comment]
@danielmarbach I just watched your presentation: Hosting and persistence with NServiceBus inside Service Fabric.
I found this to be a much smoother introduction.
First, it introduces hosting inside ASPNET.
Then it mentions an ICommuncationListener.

**Comment by danielmarbach** [comment]
Sent in a PR which should clarify our message https://github.com/Particular/docs.particular.net/pull/3588
