### ISSUE TITLE
Feedback: 'Asynchronous Handlers'

### ISSUE THREAD

**Issue by spottedmahn** [Particular/docs.particular.net#3775]
Feedback for 'Asynchronous Handlers' https://docs.particular.net/nservicebus/handlers/async-handlers

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/handlers/async-handlers.md

ping @Particular/nservicebus-maintainers

---

>[ASP.NET Core does not have a SynchronizationContext](http://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html). If you are on ASP.NET Core, it does not matter whether you use ConfigureAwait(false) or not.

[Source](https://stackoverflow.com/a/13494570/185123)

--- 

With that in mind, the docmentation does not reflect the ASP.NET Core model.

**Comment by andreasohlund** [comment]
@spottedmahn I guess you are referring to the part https://docs.particular.net/nservicebus/handlers/async-handlers#usage-of-configureawait where we recommend users to use `.ConfigureAwait(false)` ?

**Comment by spottedmahn** [comment]
>where we recommend users to use `.ConfigureAwait(false)`?

Hi @andreasohlund - yes, that is correct.

**Comment by andreasohlund** [comment]
There isn't much that I could find, perhaps https://msdn.microsoft.com/en-us/magazine/jj991977.aspx but in this case I think we'll go with just removing the section since we can't add so much value and since NSB handlers won't have a context it doesn't really matter for the enduser if they chose to omit `ConfigureAwait` or not.

Does that make sense?

**Comment by spottedmahn** [comment]
Hi @andreasohlund - thanks for the update!  Appreciate the prompt response!
