### ISSUE TITLE
Multi instance of ServicePulse is not documented

### ISSUE THREAD

**Issue by dvdstelt** [Particular/docs.particular.net#3902]
A customer created various ServiceControl instances. However when trying to look up how to create multiple ServicePulse instances, they found out this wasn't documented. Not just how to do it, but neither what you're supposed to do if you have multiple ServiceControl instances. Should they create another ServicePulse instance or not?

**Comment by danielmarbach** [comment]
Since [ServicePulse 1.20.0](https://github.com/Particular/ServicePulse/releases/tag/1.20.0) it is possible to have once instance of ServicePulse that connects to multiple ServiceControl instances. That means one instance can be used and therefore it is not required to install multiple as well as dealing with updating multiple installations. 

Closing this for now.
