### ISSUE TITLE
Feedback: 'Manipulate Pipeline with Behaviors'

### ISSUE THREAD

**Issue by MeTitus** [Particular/docs.particular.net#3921]
Feedback for 'Manipulate Pipeline with Behaviors' https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/pipeline/manipulate-with-behaviors.md

ping @Particular/nservicebus-maintainers

Hi guys,

It is not clear, at least for me, if the same instance is used per message handling or for all messages?
Does it mean that the very same instance, effectively a singleton, is used during the lifetime of the all process? And if this is indeed the case, why did you guys implemented it this way?

Thanks

"Behaviors are only created once and the same instance is reused on every invocation of the pipeline. Consequently, every behavior dependency will also behave as a singleton, even if a different option was specified when registering it in dependency injection. Furthermore, the behavior, and all dependencies called during the invocation phase, need to be concurrency safe."

**Comment by mikeminutillo** [comment]
@MeTitus 

> Does it mean that the very same instance, effectively a singleton, is used during the lifetime of the all process?

Yes. The pipeline is built once with all of the behaviors when the endpoint starts up and then that single pipeline instance is executed for every message. 

> And if this is indeed the case, why did you guys implemented it this way?

The @Particular/nservicebus-maintainers might want to step in here and correct me but I'd say efficiency. The pipeline contains a lot of behaviors and connectors and it's expensive to build. At the same time, we added the idea of the message handling context which is capable of managing the state for each individual message. It makes sense to create the pipeline of behaviors once, and then have them all work on the message state that is passed in, rather than create new behaviors every time which can manage their own local state.

We wrote a blog post about how and why the pipeline is built this way: https://particular.net/blog/10x-faster-execution-with-compiled-expression-trees

**Comment by weralabaj** [comment]
@MeTitus Seems like your question has been answered, I hope we covered everything that you looked for :)
If not, feel free to reopen this issue and follow up. 

Also, you may consider asking similar questions in the future on our discussion group http://discuss.particular.net. We monitor it so you won't be left alone. Besides, it has the additional benefit that other NServiceBus who hang out there also may learn something from your question.
