### ISSUE TITLE
Feedback: 'Outbox'

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/docs.particular.net#3947]
Feedback for 'Outbox' https://docs.particular.net/nservicebus/outbox/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/outbox/index.md

ping @Particular/servicecontrol-maintainers 
cc @WilliamBZA 

When configurating Outbox for endpoints in the system that also uses Particular Platform, it's not intuitive that outbox retention period has to consider SC failed messages retention configuration that can be infinite. Adding this information would help to connect the dots (Outbox and SC).

**Comment by mikeminutillo** [comment]
Is this to cover the following scenario?

1. Message processing is attempted and fails a number of times
2. On the final attempt, handler invocation succeeds and outbox record is successfully saved
3. Before dispatch can complete, a failure occurs. As this is the final attempt the message gets moved to the error queue
4. The Outbox retention period expires, and the outbox record is cleaned up
5. The message, having been ingested into ServiceControl, is now retried.
6. There is no outbox record for the message and so it is executed again

How common is that? What sort of failures occur in this space? Is this something we could improve automatically  rather than exposing customers to additional configuration?

For instance, does the outbox retention policy clear non-dispatched items by default? Should we be forwarding a message to the error queue if there's an outbox record for it? If we do forward a message to the error queue can we capture that info in the outbox record and treat it differently when we execute the retention policy?

**Comment by SzymonPobiega** [comment]
> For instance, does the outbox retention policy clear non-dispatched items by default?

No. We only clean up dispatched items. But the duplicate processing is still possible (although not likely) in case we mark the record as dispatched but can't ACK processing in the broker. In this case the message get to the error queue. Some transports might be more exposed to this (e.g. RabbitMQ does FLR in-memory) than others. Assuming only FLR set to N attempts, the scenario would have to look like this:
 * Message processing fails N-1 times
 * Message succeeds processing. Outbox record is stored.
 * Dispatching outgoing messages succeeds
 * Marking outbox record as dispatched succeeds
 * ACKing incoming message fails due to broker not being available
 * Moving the message to the error queue succeeds (broker is back online again)

This is probably not very likely scenario. Question is: should we even take it into account? If so then I guess we should detect that case (outbox dispatched) and not move such a message to the error queue.

**Comment by danielmarbach** [comment]
The documentation states

> After the outbox data retention period has lapsed, a retried message will be seen as the first of its kind and will be reprocessed. It is important to ensure that the retention period of outbox data is longer than the maximum time the message can be retried, including delayed retries and manual retries via ServicePulse.

https://docs.particular.net/nservicebus/outbox/#outbox-expiration-duration

This seems to address the concern. Closing
