### ISSUE TITLE
Feedback: 'NServiceBus Step-by-step: Multiple endpoints'

### ISSUE THREAD

**Issue by adriatic** [Particular/docs.particular.net#3950]
Feedback for 'NServiceBus Step-by-step: Multiple endpoints' https://docs.particular.net/tutorials/nservicebus-step-by-step/3-multiple-endpoints/

Location in GitHub: - https://docs.particular.net/tutorials/nservicebus-step-by-step/3-multiple-endpoints/#exercise-creating-a-new-endpoint

The newly added feature (copy/edit) -> copy usings (see below)

![image](https://user-images.githubusercontent.com/2712405/43677300-bf680b28-97cd-11e8-993d-00d344b31372.png)

is not implemented correctly. Only this text is copied to clipboard (missing the word `using` on each line
```
NServiceBus
System
System.Threading.Tasks
```

**Comment by adamralph** [comment]
@adriatic thanks for this feedback. As it happens, I made exactly the same observation when I reviewed the changes to the name and ordering of the dropdown. You'll be pleased to know I've initiated the process to change each line to `using {namespace};`. 😄

**Comment by adriatic** [comment]
If you really want to aim for perfection, you ought to realize the the data offered via **`Copy/Edit`** pull-down are context dependent (context being the code snippet this pull-down is attached to) 😄

**Comment by adamralph** [comment]
@adriatic I'm not sure I follow. As far as I can tell, all the items in the dropdown are already context dependent.

**Comment by adriatic** [comment]
I meant to point out that there are code snippets (like **[this one](https://docs.particular.net/tutorials/nservicebus-step-by-step/3-multiple-endpoints/#sending-messages)** for example), where the **`Copy/Edit`** dropdown offers the definition of usings, something that is not needed in this specific context where the snippets are not meant to be run, but just indicate the difference between **`SendLocal`** and **`Send`**

**Comment by adamralph** [comment]
@adriatic thanks for the explanation. I think it's reasonable to assume that, at some point in time, it could be desirable to copy _any_ snippet (they are all compiled before publishing to ensure correctness) so I think the dropdown should be there. However, in the example you pointed out, it indeed wouldn't make sense to copy the _entire_ snippet, so it should probably be two snippets instead of one.

I see there are plenty of other examples, and even some which should be split three or more, e.g. https://docs.particular.net/tutorials/nservicebus-step-by-step/3-multiple-endpoints/#routetoendpointId

@Particular/docs-maintainers thoughts?

**Comment by adamralph** [comment]
@adriatic you'll be please to know that the change has been released to put full `using xxx;` statements into the clipboard.

**Comment by adriatic** [comment]
Indeed, I **am** very pleased!
