### ISSUE TITLE
Is it OK to link to external blog posts from documentation and tutorials?

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#3963]
In the [Step by Step](https://docs.particular.net/tutorials/nservicebus-step-by-step/1-getting-started/#exercise-configure-an-endpoint) tutorial, for example, we link to an external [blog post](https://www.meziantou.net/2017/08/24/3-ways-to-enable-c-7-1-features). We have no control on the outgoing link that can 404 unexpectedly.

Shall we avoid that and bring that type of documentation in or link to what should be a more stable location over time, such as Microsoft official doco? e.g.:

* https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version
* https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1

**Comment by HEskandari** [comment]
Think there are two questions:

- Does the DocsEngine check the validity of external pages? I think it ensures the link is not dead (404). but who would check if the content is still up to date and accurate?

- Should we use blogs and web pages as a reference, or should we stick to well-known entities like Microsoft Doco? What's the criteria when we choose a link?

**Comment by DavidBoike** [comment]
Focusing on the direct issue, I chose [that blog post](https://www.meziantou.net/2017/08/24/3-ways-to-enable-c-7-1-features) because it is EXACTLY the content that is needed, presented exactly the correct way, where all the MS resources are a bit too abstracted.

On the larger/meta issue, DocsEngine currently does no HEAD requests to validate external URLs. I certainly wouldn't want to do it on every content verification build, but it is something we should do from time to time.

**Comment by danielmarbach** [comment]
Should we close this issue or bring it over to DevEd? Given that there was no traction for over a year I'm proposing to close this one unless someone strongly objects

**Comment by DavidBoike** [comment]
Closing. We should have a process to check doco URLs for 404s but that's beside the point.
