### ISSUE TITLE
Feedback: 'Docker Container Host'

### ISSUE THREAD

**Issue by mauroservienti** [Particular/docs.particular.net#3981]
Feedback for 'Docker Container Host' https://docs.particular.net/nservicebus/hosting/docker-host/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/docker-host/index.md

ping @Particular/host-maintainers 

It would be helpful if a sample can be added to the documentation for .NET Framework Classic and Windows container hosting. Because just by looking at the documentation, it's difficult to tell if this is supported on full .net framework.

**Comment by Nehmiabm** [comment]
This would really be helpful. Because the existing sample documentations are all focused on .NET Core. Adding a separate sample for Full .NET Framework Docker would be great.

**Comment by danielmarbach** [comment]
The samples are focused on .NET Core because .NET Core is the default recommended .NET Runtime for containers. That being said there are also .NET Framework images around that use Windows container underneath. Given that Microsoft is heavily pushing towards .NET Core I do think the shipped has sailed and there is no value to support a sample in so many flavors. Closing this.
