### ISSUE TITLE
Entity Framework integration should be changed to do cross db communication

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#4076]
It would be unusual for multiple endpoints to all use isolated dbs.

instead both endpoints should be separate the business db from the nsb transport db

Feedback for 'Entity Framework integration' https://docs.particular.net/samples/entity-framework/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/entity-framework/sample.md

ping @Particular/nservicebus-maintainers

**Comment by timbussmann** [comment]
@SimonCropp are you referring to the fact that the sample uses both  a `NsbSamplesEfUowNh`  and a `NsbSamplesEfUowSql` database?

**Comment by SimonCropp** [comment]
@timbussmann pretty much. in most cases i have seen endpoints have their own db for business data (and sometime co located with persistence data), but they all communicate on the sql transport via the one db. and, as i understand it, it should still work without DTC https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/transactions-always-on-availability-and-database-mirroring?view=sql-server-2017

**Comment by timbussmann** [comment]
@SimonCropp I tend to agree, however my understanding of the sample is, that these are actually two independent samples on that solution. One for nhibernate and one for sql persistence. Those sample do not communicate with each other so it's fine for them to have separated dbs. It would be a valid change to split each of the "samples" so that they would actually use dedicated databases for transport and persistence but that might be a bit overkill?

**Comment by SimonCropp** [comment]
perhaps it should be a diff sample?

**Comment by timbussmann** [comment]
reworked the sample in #4195
