### ISSUE TITLE
Feedback: 'Batching'

### ISSUE THREAD

**Issue by janpieterz** [Particular/docs.particular.net#4093]
Feedback for 'Batching' https://docs.particular.net/transports/azure-service-bus/batching

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/azure-service-bus/batching.md

I'd be interested to get some guidance on batching outside of a message handler. As the max 100 per context limitation doesn't apply. If, for example, there are 1000 messages to send and we have an EndpointInstance, is the best approach just Task.WhenAll(1000 send tasks), or batch them up in smaller batches to prevent exceeding the maximum size issues?

ping @Particular/azure-maintainers

**Comment by SeanFeldman** [comment]
Hi @janpieterz,

Great question. Probably more suited for the public forum [here](https://discuss.particular.net).
I'll answer, and if you wish to post it at the forum, feel free to add a link to the answer.

To your question aboutguidance on batching outside of a message handler.

> As the max 100 per context limitation doesn't apply. If, for example, there are 1000 messages to send and we have an EndpointInstance, is the best approach just Task.WhenAll(1000 send tasks), or batch them up in smaller batches to prevent exceeding the maximum size issues?

For performance, sending 1K messages using `Task.WhenAll` is going to be very efficient. But it comes with a cost - partial success/failure. If atomic operation success/rollback is important, batch is the way to go. Note that batch size is bit tricky, since the transport will take your POCO, convert into `BrokeredMessage`, and that one in its turn will convert the message into SBMP/AMQP message. I.e. `sizeof(poco)` is not the same as the size of an actual message sent.

Hope that information helps.

**Comment by janpieterz** [comment]
Super helpful, cheers (will ask in forum in future).

Do you think this info would be valuable in the above doc?
