### ISSUE TITLE
Documenting using multiple versions of nservicebus using binding redirects

### ISSUE THREAD

**Issue by TraGicCode** [Particular/docs.particular.net#4444]
Hello Particular team!

In the documentation for [Unobtrusive Mode Messages](https://docs.particular.net/nservicebus/messaging/unobtrusive-mode) it's stated that if you don't utilize unobtrusive messaging when using message contracts then you couple all of your endpoints to the same version of NserviceBus and they are unable have their utilized version of NServiceBus updated at their own cadence.

For those that have tried this you can actually get around this issue by adding simple binding redirects to your application's web.config or app.config that tells it which version to look for.  

**Scenario:**

Ordering.MessageContracts (NSB v5)
Ordering.Host (NSB v5)
Billing.MessageContracts (NSB v5)
Ordering.Host (NSB v5)

In the above scenario we want to update Ordering.Host to NSB v7.  It has a reference to Ordering.MessageContracts and Billing.MessageContracts.  We update the NSB version from v5 to v7 in the Ordering.MessageContracts and Ordering.Host projects like shown below:

Ordering.MessageContracts (NSB v7)
Ordering.Host (NSB v7)
Billing.MessageContracts (NSB v5)
Ordering.Host (NSB v5)

In order to allow Ordering.Host to use the Billing.MessageContracts Assembly find we need to add a binding redirect to the app.config to tell it no matter what version of nservicebus your looking for always use the version 7 one ( which will be in the bin directory ).

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
      <dependentAssembly>
        <assemblyIdentity name="NServiceBus.Core" publicKeyToken="9FC386479F8A226C" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Request**

Any thoughts on documenting this process for other developers with a warning/word of caution as i believe this would all not work if some version of nservicebus were to change a namespace for a type that one would commonly use in a message contracts assembly.

**Comment by dvdstelt** [comment]
@TraGicCode We created sample in both the old and new project styles in Visual Studio and via dark magic and compiling via command-line we got it to work, but it only makes things more complex than it already was.
In other words, we couldn't get it to work. I'm closing this, but if you have a sample where it works from Visual Studio, please do share! :-)

**Comment by DavidBoike** [comment]
To state it more clearly for anyone finding this in the future…

For binding redirects to have a prayer, the messages assembly has to be on the old version of NServiceBus, and the endpoint could be on a newer version. You'd better hope you're only touching `ICommand` and `IEvent` because if you try to touch anything else in your message assembly that changed between the NServiceBus major versions, you're not going to detect it at compile time…it's going to blow up at runtime instead.

So in theory, you could leave all your message assemblies on vOld and, one-by-one, upgrade all the endpoints to vNext. Once that was done across the entire system, you could then upgrade message assembly references to vNext.

(The reverse, a vOld Endpoint using vNext messages, is Just Not Possible using either old/new project system.)

We made a judgment call that this process was likely more complex and more error prone than just introducing conventions before starting an upgrade, especially since [starting in NServiceBus 7.4](https://particular.net/blog/whats-new-nservicebus-7-4) you can create multiple message conventions. You could even copy `IEvent` and `ICommand` into each message assembly and have a per-assembly convention. The "pit of success" path is using conventions. We also added a section to our [best practices article](https://docs.particular.net/nservicebus/best-practices) to "CONSIDER identifying message types using conventions to make upgrading to new versions of NServiceBus easier".

Those who need to venture off the beaten path (or those who need to remember why we don't directly support binding redirects 6 months from now) will hopefully find this comment.
