### ISSUE TITLE
Need ASP.NET Core 3.0 Web API sample for Publish/Subscribe pattern

### ISSUE THREAD

**Issue by ambar-ray** [Particular/docs.particular.net#4561]
I need a working sample for Visual Studio 2019 with .NET Core 3.0 as target for Publish/Subscribe pattern with NServiceBus 7.2. Please help.

**Comment by ambar-ray** [comment]
I need a working sample for Visual Studio 2019 with ASP.NET Core 3.0 Web API as target for Publish/Subscribe pattern with NServiceBus 7.2. I tried migrating the .NET Core 2.0 sample but was unsuccessful. Please help.

**Comment by dvdstelt** [comment]
Hi Ambar, thanks for your interest in NServiceBus with .NET Core 3.0
I already replied to your support request email yesterday and I hope I have answered your questions there already. But to summarize, we're currently updating our build and test environments to be able to build and test against .NET Core 3 and provide a final answer if we are 100% compatible. There are ASP.NET examples already [on our documentation site](https://docs.particular.net/samples/web/). And I wasn't 100% sure if you wanted to actually publish from ASP.NET, but [we have some documentation](https://docs.particular.net/nservicebus/hosting/publishing-from-web-applications) about that as well. In short, it's probably wiser not to publish events from websites.

Since it's easier to track conversations via support requests, I'll close this issue and possibly continue the conversation there.

**Comment by lailabougria** [comment]
Hi Ambar,

You’ve previously expressed interest in our plans of supporting .NET Core 3.1. Based on that, we wanted to get back to you to inform you that we do now fully support it.

We’ll be publishing a blog post on this subject soon, but I don’t want to keep you waiting any longer.
You can find it here: https://particular.net/blog/nservicebus-7-for-net-core-is-here

It contains a link to a sample using ASP.NET Core 3. All of our .NET Core samples are also available as download targeting .NET Core 3.1.

Let me know if you have any additional questions or concerns.
