### ISSUE TITLE
Feedback: 'SQL Persistence - SQL Server dialect'

### ISSUE THREAD

**Issue by nikolic-bojan** [Particular/docs.particular.net#4646]
Feedback for 'SQL Persistence - SQL Server dialect' https://docs.particular.net/persistence/sql/dialect-mssql

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/persistence/sql/dialect-mssql.md

Hi, it would be really great if you would add an explanation for using different DBs for transport and persistece with the **DoNotUseSqlServerTransportConnection** dialect option.

I just burned 2+ hours on this and found a solution here https://github.com/Particular/NServiceBus.Persistence.Sql/issues/144

Thanks!

**Comment by SzymonPobiega** [comment]
@nikolic-bojan so you are suggesting to improve the documentation when it comes to having separate DBs for transport and persistence?

**Comment by nikolic-bojan** [comment]
@SzymonPobiega Hi. Yes, that is my suggestion. Since configuration is clearly divided for Transport and Persistence, it is a bit odd that, by default, Transport connection is used by Persistence (I hit the wall with Saga data, but I guess that is for other stuff also).
Having a clear information in documentation that you should use **DoNotUseSqlServerTransportConnection** in those cases would be a great help.

**Comment by SzymonPobiega** [comment]
@nikolic-bojan the reason why by default SQLP uses SQLT connection is that is most cases users want to have atomic transaction that spans both persistence and transport to ensure *exactly-once message processing*.

In cases when this approach can't be used because of some sort of limitations, we recommend using the Outbox. With outbox the transport and persistence use separate connections but the Outbox guarantees *exactly-once processing* by storing messages in the persistence DB before passing them on to the transport.

`DoNotUseSqlServerTransportConnection` is for special case scenarios where you don't want the persistence to use SQLT connection and you don't want the Outbox guarantees. So basically you are on your own when it comes to de-duplicating incoming messages in order to maintain correct state.

**Comment by nikolic-bojan** [comment]
Hi Szymon,

This explanation in right on spot! This would be a great addition to a documentation on this page, if you agree.

Thank you!

**Comment by SzymonPobiega** [comment]
I created https://github.com/Particular/docs.particular.net/pull/4662 to address this. Thanks again @nikolic-bojan !
