### ISSUE TITLE
Feedback: 'Transaction Support'

### ISSUE THREAD

**Issue by mirmansoor** [Particular/docs.particular.net#4659]
Feedback for 'Transaction Support' https://docs.particular.net/transports/azure-service-bus/transaction-support

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/azure-service-bus/transaction-support.md

Under the section `Sends atomic with receive` it is mentioned that 

> TransportTransactionMode.SendsAtomicWithReceive level is only supported in Versions 7 and above of the Azure Service Bus transport

Is this referring to the Azure Service Bus Legacy transport ? because the latest version Azure Service Bus transport is only 1.4. And if so, then does that mean there is no transaction support in the new Azure Service Bus transport and we must only use the Azure Service Bus Legacy transport?

**Comment by andreasohlund** [comment]
Good catch, sends atomic with receive is available on both the old transport from v7 and up and also for the new one. @SeanFeldman can you confirm?

**Comment by SeanFeldman** [comment]
The document is re-using the same snippet for that note. Which is wrong since as @mirmansoor has pointed out.

For the new transport, `SendsAtomicWithReceive` was supported as of version 1.0.
Also, cross-namespace sending is not possible, so that part is wrong. TransportType `NetMessaging` is legacy and is irrelevant. I'd say removing that include altogether from the new transport documentation page would be the right thing to do, @andreasohlund

**Comment by SeanFeldman** [comment]
And metadata on that page was off, targetting version 7 of the package 😂

**Comment by SeanFeldman** [comment]
Thank you, @mirmansoor. PR #4663 will address this issue.
