### ISSUE TITLE
Feedback: 'NServiceBus.Extensions.DependencyInjection'

### ISSUE THREAD

**Issue by janpieterz** [Particular/docs.particular.net#4814]
Feedback for 'NServiceBus.Extensions.DependencyInjection' https://docs.particular.net/nservicebus/dependency-injection/extensions-dependencyinjection

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/dependency-injection/extensions-dependencyinjection.md

It'd be great to have a lifecycle explanation/mapping to ensure we register our items once per message handler/unit of work (or not). In our case using Autofac which maps it to an instance per lifetime scope, I'm not 100% sure on if that's how the NServiceBus extension works as well. We had some odd behavior happen on production (turned out not related) but as migrating to this was a recent change and we couldn't put a finger on the cause quite some time was spent digging to see what the behavior was.

**Comment by danielmarbach** [comment]
hi @janpieterz 

thanks for taking the time to raise the feedback. In order to better understand this can you explain what you mean with lifecycle explanation/mapping? Are you talking about some sort of a table like (from the top of my head to trigger the conversation and not aiming for correctness):

|  Scope (NServiceBus)  | ServiceCollection          | Autofac                     | Ninject | FujuitsuKungfuContainer |
|-----------------------|----------------------------|-----------------------------|---------|-------------------------|
|  InstancePerCall      | ServiceLifetime .Singleton | Instance Per Dependency     |         |                         |
| InstancePerUnitOfWork | ServiceLifetime .Scoped    | Instance Per Lifetime Scope |         |                         |
| SingleInstance        | ServiceLifetime.Singleton  | SingleInstance              |         |                         |

?

Similar to what we have in https://docs.particular.net/nservicebus/dependency-injection/autofac#dependencylifecycle-mapping summarized on that page for all the containers?

**Comment by janpieterz** [comment]
Hi @danielmarbach,

Of course, I was intending to write it myself but wanted to check first to be sure it wasn't somewhere else etc.
Something like that table is indeed exactly what I meant.

**Comment by danielmarbach** [comment]
@janpieterz I took a stab at it. I compared all the DI pages and decided to add a similar table like we have on all the other pages right before the property injection section. The PR is available at https://github.com/Particular/docs.particular.net/pull/4832

**Comment by janpieterz** [comment]
Looks great!
