### ISSUE TITLE
There is no doco on how to prepare a PROD machine

### ISSUE THREAD

**Issue by johnsimons** [Particular/docs.particular.net#491]
We should have something for OPS to prepare a machine to deploy NServiceBus in PROD.

**Comment by mauroservienti** [comment]
@johnsimons I was looking at this, have some questions:

* here http://docs.particular.net/nservicebus/preparing-your-machine-to-run-nservicebus there is no specific mention of "dev" machine, everything is done via PowerShell, am I missing something?
* where can I find difference between v4 and v5 cmdlets, if any?

the only thing I see as optional now is RavenDB, not anymore the default and not part of the core anymore.

My plan is:
* [ ] update this http://docs.particular.net/nservicebus/managing-nservicebus-using-powershell with V5 cmdlets;
* [ ] update http://docs.particular.net/nservicebus/preparing-your-machine-to-run-nservicebus to add a section related to V5 specifying that ravenDB is not required anymore, but optional

**Comment by johnsimons** [comment]
> here http://docs.particular.net/nservicebus/preparing-your-machine-to-run-nservicebus there is no specific mention of "dev" machine, everything is done via PowerShell, am I missing something?

@mauroservienti the text says "Package Manager Console inside Visual Studio", that is dev only



> where can I find difference between v4 and v5 cmdlets, if any?

I don't think there is a difference, but test it


The current issue is OPS, where do they d/l the PS cmdlets from?

**Comment by mauroservienti** [comment]
now I see, good point, I always struggle with the same issue, I end up setting up a fake VS project only to download the cmdlet nuget package.

**Comment by SimonCropp** [comment]
a little history... this http://docs.particular.net/nservicebus/preparing-your-machine-to-run-nservicebus is the page that developers were sent to when installin older versions of the NSB nugets. 

This is no longer the case but u need to be aware that people can still install those old nugets and the page need to be contextual to that action

**Comment by gbiellem** [comment]
Hi @mauroservienti 

And for V5 users we have something new that I'm about to release after Cyprus

Some time back @andreasohlund pulled the infrastructure specific cmdlets out of the core and created the NServiceBus.Powershell repo.   I've  cleaned these upand turned them into a standalone powershell library that can be installed via an MSI,   

The idea being that these cmdlets can be installed on any PC OPS users want to prep. 
The cmdlets vary a little from what was previously in NSB v4.

If you to review them here is the current [beta](
https://builds.particular.net/repository/download/NSB_PS_CreateInstaller/65386:id/Particular.NServiceBusPowershell-5.0.0-beta.1.exe)

The assembly is CLR 2 compliant so it's compatible with PS v2, 3 and 4  without hacking any powershell.exe.config files like our old doco told OPS to do. 

Also Because we aren't defaulting to installing RavenDB any more there is no longer a cmdlet provided to install it.

To install and test run the MSI and then open an Admin PS Prompt 
```
Import-Module NServiceBus.Powershell
Get-Command "*NServiceBus*"
```
Each cmdlet has proper help unlike the old ones so for instance 
```
PS C:\Users\Test> Get-Help Install-NServiceBusPerformanceCounters

NAME
    Install-NServiceBusPerformanceCounters

SYNOPSIS
    Adds NServiceBus performance counters on this machine.


SYNTAX
    Install-NServiceBusPerformanceCounters [-Force [<SwitchParameter>]] [<CommonParameters>]


DESCRIPTION
    This cmdlet adds the "NServiceBus statistics" Performance Monitor category.
    Underneath this category the following counter are added:

    - Critical Time
    - SLA violation countdown
    - # of msgs successfully processed / sec
    - # of msgs pulled from the input queue /sec
    - # of msgs failures / sec

    Use the Test-NServiceBusPerformanceCountersInstallation cmdlet to verify the counters exist.


RELATED LINKS
    Test-NServiceBusPerformanceCountersInstallation
    Uninstall-NServiceBusPerformanceCounters
    http://docs.particular.net

```

**Comment by mauroservienti** [comment]
Amazing :-)
I'll test them and setup the new documents.

Sent from my Amazing not anymore Yellow Lumia, typos are guaranteed ;-)

-----Original Message-----

**Comment by weralabaj** [comment]
@mauroservienti @johnsimons @gbiellem is that issue still relevant given we have installer? if so, could you replace this with a new one with a better defined PoA?
