### ISSUE TITLE
What version of the sql transport supports batching?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#5030]
Feedback for 'Batched message dispatch' https://docs.particular.net/nservicebus/messaging/batched-dispatch

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/messaging/batched-dispatch.md

What version of the sql transport supports batching?

**Comment by SimonCropp** [comment]
paging @SzymonPobiega @danielmarbach

**Comment by SimonCropp** [comment]
the reason i ask is this is still open https://github.com/Particular/NServiceBus.SqlServer/issues/143

**Comment by SzymonPobiega** [comment]
Frankly I am not sure what the issue was about 😕 Might refer to
 - using a single SQL statement to batch multiple inserts (something NHibernate does if I am not mistaken) if multiple messages are sent to the same destination queue
 - implementing session-like API for sending outside of a handler where you can send multiple messages in a "transaction" -- this is now sort-of supported by providing external transaction

**Comment by danielmarbach** [comment]
Sorry @SimonCropp unfortunately, I don't have enough context to answer your question.

**Comment by mikeminutillo** [comment]
@SimonCropp All of the supported versions of the SQL Transport support the type of message batching described in the linked documentation. That batching is only applicable to outgoing messages which are sent/published within a message handler. All outgoing messages are captured in memory and then handed off to the transport in a single batch once all of the handlers have completed.

**Comment by SimonCropp** [comment]
@mikeminutillo thanks for the clarification
