### ISSUE TITLE
Feedback: 'NServiceBus Host Upgrade Version 6 to 7'

### ISSUE THREAD

**Issue by bennettwork** [Particular/docs.particular.net#5154]
Feedback for 'NServiceBus Host Upgrade Version 6 to 7' https://docs.particular.net/nservicebus/upgrades/host-6to7

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/upgrades/host-6to7.md

Shouldn't there be a page for "NServiceBus Host Upgrade Version 5 to 6"?

It's confusing that the first line of "NServiceBus Host Upgrade Version 6 to 7" says

> This is part of the NServiceBus Upgrade Guide from Version 5 to 6...

The mismatching vesion numbers are confusing. Anyway, there currently appears to be no ducumention about upgrading from NServiceBus Host 5. I think there should be!

**Comment by ramonsmits** [comment]
@bennettsolnet you are right that is seems an upgrade guide from Host 5 to 6 seems to be missing.

However, Host v6 is part of Core v5. We follow Semver which required incrementing the major version because we introduced a breaking changes in Host v6:

https://github.com/Particular/NServiceBus.Host/releases/tag/6.0.0

The breaking changes is:

> Previous versions enabled the performance counters Critical Time and SLA violation countdown by default. 

I do not expect any other issues and because there do not seem to be any "compile" issues it seems the upgrade guide was skipped. 

Thanks for making us aware of this gap and I'll create the missing upgrade guide with this info at a later moment.

**Comment by soujay** [comment]
As per the [document](https://docs.particular.net/nservicebus/hosting/nservicebus-host/) , NServiceBus.Host  version 5 and version 6 , both target NSB 5.x which is out of [support](https://docs.particular.net/nservicebus/upgrades/supported-versions). We didn't provide an upgrade guide for NServiceBus.Host going from 5 to 6 as there was not any breaking change
