### ISSUE TITLE
Feedback: 'Migrating from timeout manager to native delivery'

### ISSUE THREAD

**Issue by mortenn** [Particular/docs.particular.net#5589]
Feedback for 'Migrating from timeout manager to native delivery' https://docs.particular.net/nservicebus/tools/migrate-to-native-delivery

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/nservicebus/tools/migrate-to-native-delivery.md

The page does not seem to indicate what runtime/sdk is needed for the tool.
When I tried installing it, I got this error;
```
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'tool' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
```

**Comment by DavidBoike** [comment]
Currently it's built for .NET Core 3.1. I really do wish NuGet would display that information. We don't target .NET 5 because we don't want to target tools to .NET versions that do not have LTS support.

We are in the process of updating everything for .NET 6 and as part of that, we'll update the tool to also target .NET 6. You can follow that effort here: https://discuss.particular.net/t/nservicebus-support-for-net-6/2525 As a part of that effort I'll see if we can improve the documentation to make the necessary .NET version evident.
