### ISSUE TITLE
Add information about Azure ServiceBus

### ISSUE THREAD

**Issue by sfarmar** [Particular/docs.particular.net#578]
“Personally I don’t compare NServiceBus to Azure Servicebus, they are not the same thing. Azure servicebus is messaging infrastructure, while NServiceBus is a productivity library on top of messaging infrastructure. NServiceBus can use Azure Service Bus as a transport, and adds quite a few things on top. Next to the regular nservicebus features (handlers, ioc integration, auditing, saga’s, timeouts, etc…) it provides the following specifically for azure:

Easy serialization and deserialization of explicit message types, with azure servicebus you’re basically parsing strings yourself.
Automated queue, topic & subscription management, in azure servicebus you need to set these up manually
A DataBus for messages that have properties that would exceed the maximum message size of azure servicebus (256K)

We also have a shared hosting model for web & worker roles that allows you to host multiple endpoints on single worker roles in different processes, basically you co-locate your roles, which brings significant cost benefits as well as maintenance benefits over the traditional hosting model implied by visual studio. You don’t need at least 2 machines per logical role, you only need 2 machines and put all your roles on there until you need to scale out. Deployments also take seconds instead of 15 minutes, makes life a lot easier.
It also implements smart backoff mechanisms in the transport, further driving down your costs of accessing azure servicebus, especially when no messages are present in the queue (you pay per request, not per message, this is an often overlooked ‘detail’, until users get their first bill)

And last but not least, the nservicebus programming model gives you an abstraction over all these concepts, and thus an abstraction over windows azure. If you ever decide to leave azure (to go to another datacenter or cloud vendor), you are not tied to the azure platform and can migrate with little effort. Just switch to another transport and storage and you’re done.
Hope this helps?

Kind regards, Yves"

“A couple of things to note @seanfarmar @daniel.marbach

1. Deployment story – I’d say “updates can be deployed magnitudes faster and do not require Cloud Services re-deployment”. Specific times may vary on size of package, # of endpoints, # of additional assemblies, etc.

2. Multihost/shared host is is for worker roles, not web roles (http://docs.particular.net/nservicebus/hosting-nservicebus-in-windows-azure#cloud-services-shared-hosting).

In regards to #2, one could run a web app that is not IIS based (Like NancyFX or OWIN)
Sean Feldman"

Here is a presentation Yves gave at NSBCon London 2014:
https://skillsmatter.com/skillscasts/5106-nservicebus-on-the-windows-azure-platform

/cc @yvesgoeleven @SeanFeldman

**Comment by udidahan** [comment]
Shouldn't there be some representation of this on the website itself, and not just in docs?

@brittking and @Particular/marketing ?

**Comment by danielmarbach** [comment]
I think we need to broaden this to transports in general. Last week a customer asked me why he would require NServiceBus and not just build something on top of MSMQ or ActiveMQ. I gave him this answer:

> Regarding MSMQ and ActiveMQ. What you are talking about is directly using the transport layer. This is certainly an approach you can go for. Although in my point of view this has the following disadvantages:
General:
Falling down to the transport layer directly means you have to solve all the problems yourself in your own code base. For example
•	You are building your own threading/consuming infrastructure which has to deal with exception handling, first and second level retries, cancellation, adaptive threading and more
[Solved for you by the Particular Platform]
•	You have to translate/serialize your business messages into the low level messages and build that infrastructure yourself
[Solved for you by the Particular Platform]
•	The transports API are super low level. What is missing is an infrastructure for your developers to quickly solve business problem without worrying about the underlying transport mechanism
[Solved for you by the Particular Platform]
•	You need to come up with concepts how to solve auditing of messages, error queue handling, routing and much more
•	We implement all the message patterns on top of the transport API which you are going to need to build a reliable system based on messaging like Request/Response, Callbacks, Fire & Forget, Correlations, Conversations, Stateful process managers, scheduling…
[Solved for you by the Particular Platform]
•	Backwards compatiblity. We are wire compatible over multiple versions and test that constantly. We would need to build the testing infrastructure yourself and maintain it
[Solved for you by the Particular Platform]
•	Wen a transport is officially supported by particular we make sure that we have the necessary resource in-house that fully grasp the transport and its concepts behind. Combined with the support levels we provide you essentially get around the clock support for everything we provide.
MSMQ:
•	Msmq is a so called store and forward mechanism using a point to point communication protocol. If you want to do publish/subscribe you essentially have to build up an infrastructure on top of MSMQ which allows to do multi-cast communication
[Solved for you by the Particular Platform]
•	We fine tuned MSMQ usage so that you get the maximum performance out of that technology
About ActiveMQ. We currently do not officially support ActiveMQ. I have been building an ActiveMQ transport implementation for NServiceBus in the past and using it in production. I can say from my own experience that ActiveMQ together with .NET is not an infrastructure I would put my trust into. The following discussion highlights all the issues there:
https://groups.google.com/forum/#!searchin/particularsoftware/activemq/particularsoftware/2QWOxQsgusw/Bl_Nw02FpsYJ
https://groups.google.com/forum/#!msg/particularsoftware/FiumuWizUXI/-QWME-qL1wMJ

Can we rename this doco taks to something broader? Thoughts?

**Comment by udidahan** [comment]
Put it on the tasks repo and run with it there.

**Comment by danielmarbach** [comment]
The whole issue and therefore closing this one?

**Comment by udidahan** [comment]
There may be some info that is better left in the docs site but that will ultimately be uncovered by working through the task for the website.

**Comment by udidahan** [comment]
So, yes.

**Comment by danielmarbach** [comment]
Moved to https://github.com/Particular/Tasks/issues/147
