### ISSUE TITLE
Feedback: 'Configuration Settings'

### ISSUE THREAD

**Issue by fourpastmidnight** [Particular/docs.particular.net#6037]
Feedback for 'Configuration Settings' https://docs.particular.net/servicecontrol/creating-config-file

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/servicecontrol/creating-config-file.md

For v4.x of ServiceControl, on the page listing the settings for the Audit instance, the default `MaximumConcurrencyLevel` for SC v4.12.0+ is 32. Prior to this version of ServiceControl, the default value was 10.

On the page referenced above for the primary/error instance, this same setting states a default value of 10. Has this default value changed for the primary instance as of ServiceControl 4.12.0?

**Comment by dvdstelt** [comment]
Hi @fourpastmidnight ,

For error instance: https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Infrastructure/Settings/Settings.cs#L44
For audit instance: https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl.Audit/Infrastructure/Settings/Settings.cs#L36
For monitoring instance: https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl.Monitoring/Settings.cs#L28

I am not aware of a specific reason why it's set to 10 on the error instance, but 32 on audit and monitoring.

Does this answer your question or do you have follow up questions?

**Comment by dvdstelt** [comment]
Your original question was whether or not it was changed for the primary/error instance, that's why I looked up the default settings for you :-)

_Why it's 10_ for that instance is a valid question as well though. The default of 32 on the other instances was introduced when we started batching inserts via the bulk load session. It was left at 10 for the error instances because [tests](https://github.com/Particular/ServiceControl/pull/2477) showed a larger batch size wasn't beneficial for the error instance.

**Comment by fourpastmidnight** [comment]
OK, so, you said tests showed there was "no benefit", but, would it _hurt_ if the error instance was set to a `MaxConcurrencyLevel` of 32? I suppose if I were to run the error _and_ audit instance on the same machine, I would want to be careful with that, however.

**Comment by dvdstelt** [comment]
You are correct. It won't hurt if you set it to 32, but it might influence performance. It's hard to tell how much and if it improves or worsens performance.
