### ISSUE TITLE
validating messages

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#607]
Two types of validation
### Infrastructure validation

Check incoming messages for non business related data. Some examples
- authorization/authentication keys/tokens in headers
- serialization/message format issues

Infrastructure errors will be generally be forwarded to the error queue
### Business model validation

Validation errors that can be related to specific business scenarios Some examples
- User already exists
- phone number invalid

Business model can generally be integrated into the business process and appropriate actions taken on the specific error or just a generic response of "here is a list of errors"
## The plan
- Document the above two including the extensions points that would be sued to facilitate them
- build a working sample that show the two in conjunction with  https://github.com/JeremySkinner/FluentValidation

**Comment by SimonCropp** [comment]
@andreasohlund so we talked about this already. you mentioned some existing guidance around validating messages, can you point to that?

**Comment by andreasohlund** [comment]
Do you mean how users should validate the data in their messages? Or us validating that the users message is structured in a sane way from a schema perspective? (Eg. No use of `dynamic` or `object`)

**Comment by SimonCropp** [comment]
@andreasohlund the first one :)

**Comment by andreasohlund** [comment]
The guidance I've seen/given/hear of is to use Ctor args + private sets for commands to make sure they are created in a valid state. Since we recommends (needs to be discussed as well) interfaces for events we've just said that since events are published after the fact and mostly contains ID's the user should be fine with no specific validation. They can of course slap on DataAnnotations or something similar if they are paranoid.

That's really all I remember, @udidahan ?

**Comment by udidahan** [comment]
We’ve seen people doing “fat” events, but that doesn’t mean that a subscriber can invalidate it either.

**Comment by SimonCropp** [comment]
not worth doing for now. if anyone wants to get around to this please submit a PR
