### ISSUE TITLE
Feedback: 'Transport Transactions'

### ISSUE THREAD

**Issue by shirin-monzavi** [Particular/docs.particular.net#6128]
Feedback for 'Transport Transactions' https://docs.particular.net/transports/transactions

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/transactions.md

Dear sir or madam,
I am not a native speaker and reader. it is really hard to find out the intention of most of your articles. I can feel that your writers are professional and it is hard for them to explain everything widely. But we are co-worker and I need to understand everything in order to know which transport system is suitable. So I beg to your writers to write more and explain everything in a more detail with a great picture. because as a consumer I get confused. which is better for me. on top of that, I am a user and I need your library so I need to know why should I use it and when I should use it. for example: what is ghost messages? or what is Sends atomic with Receive?
you can write all of your articles like: what? problem? solution? how? with example.
this format is the best one.

your faithfully

**Comment by shirin72** [comment]
what is difference between Sends atomic with Receive and only receive?

**Comment by soujay** [comment]
@shirin72 - Thank you for your feedback and your suggestions for improving our docs site .



> what is difference between Sends atomic with Receive and only receive?

**ReceiveOnly :**

In this mode the receive operation is wrapped in a transport's native transaction. This mode guarantees that the message is not permanently deleted from the incoming queue until there is at least one processing attempt (including storing user data and sending out messages) finished successfully.

Eg: In Azure Service Bus and Azure Storage Queues, the message is not removed from the queue after it is received, but rather its hidden for some duration. This prevents other instances from receiving the message. If the receiver fails to process the message within that time frame or explicitly abandons the message, then the message will become visible again. Other instances will be able to pick it up (effectively rolling back the incoming message).

**SendsAtomicWithReceive:**

This mode is similar to the ReceiveOnly, but transaction is shared with sending operations as well. That means the message receive operation and any send or publish operations are all committed atomically i.e., all outgoing operations are atomic with the ongoing receive operation.

**Comment by soujay** [comment]
@shirin72 

**Ghost Message:**

Consider a scenario where say a user(student) is created in a database and then a user created event is published so that the next set of steps like say assigning classes, teacher, id cards can take place. These two steps namely creating the user and publishing the user created event take place inside a message handler. If due to some mishap the user is not created in the database, but the user created event is published then, the rest of the system is notified about the creation of the user who does not exist in database. This causes further errors in other message handlers which is expecting the user to exist in the database. Such a message is called a Ghost message.

**Comment by shirin72** [comment]
I really appreciate you because of your answer. 
I will state it again for you to see whether I get it or not.

Receive only:
there is message (user is created). there are some handlers such as; welcome email, discount for registration and so forth..
handler number one (welcome Email) receive the message but it cannot handle it because of some reasons.
as a result, the message will not be sent to other handlers(discount for registration) and message is remained in the queue for a while. after some time out the message will be sent again to that handler(welcome Email) then if the message is processed in that handler so the other handlers( discount for registration) gets that message.

SendsAtomicWithReceive:
consider that scenario again.
the message is sent to a handler (welcome email) and then handler will face an error. and in this handler there is another message (email is sent) which should be sent to another endpoint (customer gift). if our handler(welcome email) will face an error and another message(email is sent) which is sent to another endpoint ((customer gift)) will be rolled backed.

thank you in advance

**Comment by shirin72** [comment]
Dear sir or madam
I really appreciate you
Yours faithfully
