### ISSUE TITLE
Explain the alternatives for subscribing on your own events

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#621]
Sometimes users subscribe to their own events. This usually results in unneeded complexity. Explain how SendLocal can help reduce this complexity with its pro's and con's.

**Comment by SimonCropp** [comment]
Pretty sure sendlocal on a event is an antipattern we never want to recomend. What r the pros?

I doubt it even works. Doesnt the conventions stop it?

**Comment by DavidBoike** [comment]
I like subscribing to my own events. Even if there's only 1 subscriber. It leaves the door open for additional decoupled subscribers later.

**Comment by ramonsmits** [comment]
@SimonCropp @DavidBoike Isn't it strange that a service subscribes to itself? I would not do `SendLocal(IEvent)` I would just send an internal command. If I would require the need to subscribe on my own events to add decoupling then I would probably create multiple endpoints.

@DavidBoike I really do not like the fact of adding multiple event handlers in that same endpoint as these are executed in the same transaction. Much better IMHO to have seperate commands for each handler executing on the same endpoint but different transactions.

**Comment by ramonsmits** [comment]
The same applies then to `Bus.Send(..)` as when you have the `UnicastBusConfig/MessageEndpointMappings` section configured then you could use that instead of `Bus.SendLocal`.

So we have not a `Bus.PublishLocal` but that is I think due to avoid having multiple event handlers for a single event. Is this correct?

I don't say drop the `Bus.Publish` as that event could still be of interest for other services bus I would do:

    Bus.Publish(Events.SomethingHappened);
    Bus.SendLocal(Commands.IncreaseUserCount);
    Bus.SendLocal(Commands.SendConfirmation);

What is your opinion on this?

**Comment by andreasohlund** [comment]
Imo it's valid to subscribe to your own events like @DavidBoike mentions. It might be denormalization event handlers etc. Sometimes you're not ready to split your system up into endpoints just yet and choose to host components from different services in the same endpoint. Not sure if this would change if we had a better multihost.

I'd don't see the connection btw sendlocal since that would change the meaning of the message from a `event` to a `command`

That said we should document the use case for sendlocal, ie to split work up into async chunks by using sendlocal. Eg fetching a set of orders from a db and do a bus.SendLocal(new DispatchOrder(orderId)) for each one of them.

Interesting enough this would be a use for callbacks to fetch/dispatch a new batch when all work items is complete?

**Comment by SimonCropp** [comment]
ok I am closing this. i cants see hos this doco can make sense given the above comments
