### ISSUE TITLE
Feedback: Add sample that shows Managed Identity with azure function 4 in isolated mode

### ISSUE THREAD

**Issue by mennolaan** [Particular/docs.particular.net#6361]
Feedback for 'Configuration' https://docs.particular.net/transports/azure-service-bus/configuration

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/transports/azure-service-bus/configuration.md

Managed Identity with azure function 4. in isolated mode is unclear. Please provide a working example that applies managed identity. How do we need to supply the variable ? Is it AzureWebJobsServiceBus:fullyQualifiedNamespace or AzureWebJobsServiceBus? What does the value look like?

**Comment by awright18** [comment]
@mennolaan We have some upcoming work focusing on Managed Identity. I've made sure this feedback is referenced in the documentation related to that work. This work will likely include documentation updates explaining how to correctly use Managed Identity for various Azure use cases.

**Comment by mennolaan** [comment]
Thank you! Looking forward to it.

**Comment by andreasohlund** [comment]
@mennolaan we've released support for this in 5.1 https://discuss.particular.net/t/nservicebus-azurefunctions-worker-servicebus-5-1-0-minor-release-available/3984 and since we have docs on how to use managed identities we don't believe a sample is needed.

https://docs.particular.net/nservicebus/hosting/azure-functions-service-bus/#configuration-servicebus-connection

Closing this
