### ISSUE TITLE
Move Platform pages to a top level menu item

### ISSUE THREAD

**Issue by kbaley** [Particular/docs.particular.net#6585]
The [Service Platform](https://docs.particular.net/platform/) pages are buried under the NServiceBus menu item when they talk about the entire platform. They would be better served as a top-level menu item (possibly above NServiceBus and below Architecture.

Besides the page above and all its subpages, consider moving these pages under the same top-level heading:

- https://docs.particular.net/platform/contributing
- https://docs.particular.net/nservicebus/release-notifications

The new top level menu item will need an icon, probably the one associated with the Particular Service Platform.

**Comment by soujay** [comment]
## 🚀 This is done



### ✔ What has been done



- The [Service Platform](https://docs.particular.net/platform/) pages have been moved as a top-level menu item 

### 🏺 Artifacts



- None

### 🏠 Town hall notes


- None

<sup>[📝](https://github.com/Particular/StaffSuccess/blob/master/github/saved-reply-templates.md#closing-issues) [guidelines](https://github.com/Particular/StaffSuccess/blob/master/guidelines/facilitation.md#closing-issues) version 2024-01-25</sup>

**Comment by sergioc** [comment]
@soujay a couple of comments about the implementation:

- The icon you used is from the company logo. This is the actual icon for the platform: https://github.com/Particular/DeveloperEducation/blob/master/brand-style-guide/Icons/SVG/Particular_Service_Platform.svg
- There's no need to spell out `Particular Service Platform`.  Just `Service Platform` should be enough
- It shouldn't be necessary to expand a lonely "General" sub-category under the Service Platform in order to access actual content. As it is now, it doesn't make the content truly top-level.

**Comment by soujay** [comment]
@sergioc - I will open another PR to apply your suggestions
