### ISSUE TITLE
Create guidance for moving from InProcess to Isolated Worker model

### ISSUE THREAD

**Issue by dvdstelt** [Particular/docs.particular.net#6781]
Microsoft announced that Azure Functions InProcess model [will receive its last update with .NET 8](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/net-on-azure-functions-august-2023-roadmap-update/ba-p/3910098). This version of .NET has already been out for a while at the time of writing, but there hasn't been an SDK update for isolated functions yet, which we expect is Microsoft's way of warning users to migrate to the Worker model. We already [encourage customers to not start new projects with InProcess functions](https://docs.particular.net/nservicebus/hosting/azure-functions-service-bus/in-process/).

For customers that already use NServiceBus Azure Functions InProcess we need a migration guide to allow them to migrate to Isolated Worker functions. A guide that explains to them how to switch NuGet package and potentially take additional steps to migrate.

**Comment by TravisNickels** [comment]
The migration guide for in-process to isolated worker model has been added to the docs site: https://docs.particular.net/nservicebus/upgrades/azure-functions-service-bus-in-process-isolated-worker

**Comment by andreasohlund** [comment]
@TravisNickels The isolated model [doesn't support "AtomicSendsWithReceive"](https://docs.particular.net/nservicebus/hosting/azure-functions-service-bus/#configuration-transactions), I didn't see that pointed out in the guide, was that considered?

**Comment by TravisNickels** [comment]
> The isolated model [doesn't support "AtomicSendsWithReceive"](https://docs.particular.net/nservicebus/hosting/azure-functions-service-bus/#configuration-transactions), I didn't see that pointed out in the guide, was that considered?

There was discussion about not repeating information and there is a reference to that documentation in the related articles section. 

I did have a more in-depth discussion with Daniel about "SendsAtomicWithReceive", but it was after this PR was already merged. However, I'm definitely open to the idea of explicitly including that in this migration guide, if we think it would be beneficial.

**Comment by andreasohlund** [comment]
Had a chat with @danielmarbach and we think its worth pointing out since if you have atomic sends enabled (not on by default) for the in-process model you would have to adjust things when migrating.

The adjustments would be:

1. (My preferred) Start using the outbox https://docs.particular.net/architecture/consistency#transactions-outbox-pattern
2. Ensure that all handlers involved are idempotent https://docs.particular.net/architecture/consistency#idempotency


Does this make sense? (happy to help out with the exact wording)

**Comment by TravisNickels** [comment]
Yeah, that makes sense.

I'm assuming that because the [worker model](https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/blob/0169ca5de7c86a126ddf1830160ede48af31b495/src/NServiceBus.AzureFunctions.Worker.ServiceBus/NServiceBusTriggerFunctionAttribute.cs#L8) doesn't have a `SendsAtomicWithReceive` assembly attribute like the [in-process model](https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/blob/743f8c967ba45c93d20a24aaa1617bc55345a56f/src/NServiceBus.AzureFunctions.InProcess.ServiceBus/NServiceBusTriggerFunctionAttribute.cs#L23) does, that it's not possible to even change the transaction mode.  Is that correct?  

That would mean if a user had

```csharp
[assembly: NServiceBusTriggerFunction("ASBFunctionEndpoint", SendsAtomicWithReceive = true)]
```

They would need to remove `SendsAtomicWithReceive = true`. Then implement outbox and/or configure all handlers to be idempotent.

I will raise a new PR to address the changes and ping both of you for a review.

**Comment by andreasohlund** [comment]
>I'm assuming that because the [worker model](https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/blob/0169ca5de7c86a126ddf1830160ede48af31b495/src/NServiceBus.AzureFunctions.Worker.ServiceBus/NServiceBusTriggerFunctionAttribute.cs#L8) doesn't have a SendsAtomicWithReceive assembly attribute like the [in-process model](https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/blob/743f8c967ba45c93d20a24aaa1617bc55345a56f/src/NServiceBus.AzureFunctions.InProcess.ServiceBus/NServiceBusTriggerFunctionAttribute.cs#L23) does, that it's not possible to even change the transaction mode. Is that correct?

That is correct, the reason is that the worker SDK doesn't (at least yet) have a way to marshal the transaction over the process boundary.

>They would need to remove SendsAtomicWithReceive = true. Then implement outbox and/or configure all handlers to be idempotent.

Correct
