### ISSUE TITLE
Add doco about securing ServicePulse 

### ISSUE THREAD

**Issue by sfarmar** [Particular/docs.particular.net#755]
This blog by [Danny Fafach is a great starting point[(https://fafach.wordpress.com/2014/10/24/securing-servicepulse/)

**Comment by gbiellem** [comment]
There is nothing to secure is SP - It has no data!

That blog post is in fact dangerous as it gives the illusion of security.  All he has managed to secure access is access to the the static HTML and JS files. 

Since SP requires access to the SC rest API he would have to expose SC to the work to make this worthwhile.  So a quick script later and a hacker has every dumped out every message stored in his SC.

**Comment by gbiellem** [comment]
I'm closing this. I don't want to further propagate the illusion of security by adding this to our doco.
Even Danny Fafach rightly points out the flaws in his approach - and that to address security properly  Particular need to provide an auth and access control layer to service control.
