### ISSUE TITLE
Transport selection guidance

### ISSUE THREAD

**Issue by DavidBoike** [Particular/docs.particular.net#786]
I know, this has already been brought up a few times.
#134, #562, Particular/Stories#2

It seems as though it got started as a Docs issue, then thrown over the wall into Stories, and then both pointed a finger at the other and both got closed. Meanwhile @mauroservienti wrote some [pretty amazing content](https://github.com/Particular/docs.particular.net/blob/31620e74c8acf60eabc16acb65e130ef39ae1608/nservicebus/transports/comparison.md) but, probably rightly, it was decided that keeping that level of content up-to-date and relevant would be impossible.

There is a need for this guidance content, and it has to be in our docs. People say "I'd like to start using your software" and the first thing we say is "OK you need to pick a transport and a persistence." Customer says "OK how do I do that?" And we say...? Not much of anything. A blog post is not right, as that's not where people who need the information are going to be looking.

The problem with @mauroservienti's attempt is that it tried to go too granular. Most of those differences we whitewash over anyway. The guidance docs should only cover the high points that I would go over with a prospective customer on a technical call. Thus it wouldn't be a comparison of specific queue features, like number of supported queues. Those kind of limits are never reached. It needs to be stuff like you shouldn't run Rabbit on Windows, so if you don't feel comfortable maintaining a Linux cluster, don't pick that.

This will, to some extent, be opinion-based. However, it's our job to have these opinions. We just need a different section of doco to call out that this is guidance, not facts about API. I propose a root-level "guidance" folder that would group this and future article. (At least [how to choose persistence](https://github.com/Particular/docs.particular.net/issues/787), as it's the other thing we make you pick up front.)

So, I will be taking a stab at writing this. Looking for feedback on where to place it (I really think a new section is needed, "guidance" is my first stab at a name) and how to link it in to the rest of the site.

**Comment by SimonCropp** [comment]
from slack:

i will withhold judgement until i see some content. but it is very hard to write that type of guidance in a way that both doesnt need the context of the customer and is in any way actually applicable to NSB

Or in other words, I never have encountered TAM/consultative “What’s best?” in those areas.

i would prefer a "want help chosing a transport... we offer consulting services to help you with you architectural choices"

it is like someone asking "should i use oracle or sqlserver for my transport".  that is not something our doco should own.or should i use x version of windows server. or logging lib, or serialization, or container.

i understand we get asked the question regularly. but that does not always mean we should document it. people also regularly ask us about assembly loading and binding redirect issue.  but we should not own the doco about that

i think i would prefer doco on "why we cant give you advice on choosing a transport or persistence AKA since we have no context" and then point them to some example google search links

then that ticks the box of we have an response without trying to articulate something that is not possible to capture

**Comment by SimonCropp** [comment]
how about a compromise. i propose a "list of things you might consider when choosing a transport"

* what existing skill set your people have for both developing and maintaining...
* throughput for your scenario (your hardware + message size + network etc)
* cost of transport including initial purchase, support, per message cost, message size cost
* is it open source so u can diagnose issues yourself
* active community
* supported operating systems
* message size limitations
* is it cloud friendly if you one day plan to move to the cloud

And we dont mention the specifics of any transport for the about since in most cases the answer is "it depends".

This is significantly less effort than us documenting the transports and helps the consumer do their own homework

**Comment by mauroservienti** [comment]
I like the idea, what about addiong to the above list:

* transaction support
* consistency model

They are important at decision time and at this stage we know that the `Outbox` does not cover all the scenarios.

**Comment by weralabaj** [comment]
@DavidBoike @SimonCropp @mauroservienti Given that such guidance should be carefully reviewed, and that it's a fair amount of effort I'm tempted to move this issue to Plat Dev, together with https://github.com/Particular/docs.particular.net/issues/787. If you don't object, I'll move it tomorrow.

**Comment by weralabaj** [comment]
Move to plat dev https://github.com/Particular/PlatformDevelopment/issues/1252
