### ISSUE TITLE
Better guidance around when and why we crash the endpoint on purpose

### ISSUE THREAD

**Issue by andreasohlund** [Particular/docs.particular.net#870]
Got this question on the group:

> So are we still saying that on a timeout, a crash is still the expected outcome. This does not sit well with me.

I answered

> The reasoning is that we keep on retrying for 2 minutes/what ever you configured and if we still can't reach the DB will give up and stop the host. We do this since if we can't talk to the DB in this case we can't dispatch timeouts in a timely manner. 
> 
> Stopping the host serves 2 purposes:
> 1. If there is any issues with the actual process stopping it will hopefully solve it once restarted (leaked connections etc)
> 2. Draws attention, should users not monitor their logfiles for errors they will at least notice that the host is down

And gave this recommendation

> - Set the timeout value to something that makes sense for your environment, perhaps 2 min is to short? (FYI: https://github.com/Particular/NServiceBus/issues/2994)
> - Make sure your host is setup to restart automatically 
>   - https://technet.microsoft.com/en-us/library/bb490995.aspx
>   - Eg. sc.exe failure MyEndpoint reset=86400 actions= restart/120000/restart/120000/restart/120000

Do we agree with my statements? 

If yes where on docs does this belong? (Under the http://docs.particular.net/nservicebus/operations/ section?)
### Original thread

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/SI2T6SH8un0/IUiMnsUMBAAJ

**Comment by ramonsmits** [comment]
Not only guidance, if you ask me then this needs to be an explicit choice for both enabling or disabling of the circuitbraker(s) in v6.

**Comment by andreasohlund** [comment]
We want to be "production ready be default" would you argue that us shutting down is violating that?

**Comment by ramonsmits** [comment]
@andreasohlund It has two angles which are hosting and embedding and in both we fail as the behavior is implicit. How many products do you know that really kill them selves?

We should be reliable by default and also be reliable for the process in which we are embedded meaning that we need to be a good neighbour. We should not close the door by default as this causes issues for the tasks that depend on us.

From a hosting perspective I can sort of understand it. Windows services should have recovery enabled but when an endpoint is embedded into a process like a web application then this behavior really needs to be explicit. Now its hidden, causing all kinds of issues for customers like broken apps because nservicebus decided to dispose itself because the circuit-breaker triggered this.

A more sensible default would be to have a sort of 'backoff' strategy, delaying execution in combination with recovery. Another strategy is to actually KILL the application by default with an application exit. Current behavior is that we only dispose ourselves, the instance is still called by others resulting in strange exceptions of which the callee cannot recover easiliy. In case of a web app killing the process will atleast result in a new instance of the web app to be started.

An even more serious related issue is that we dispose the container that is externally passed to us. The circuit braker disposes this instance which  result in the whole application to be potentially be in a failed state. How will a sysadmin understand what is causing all those object already disposed exceptions? Just do a magic restart to solve this problem.

I'm really 100% for making these behaviors explicit in the configuration API.

Also, the circuit breaker strategy should be pluggable.

In certain environments it makes sense:

- to ignore incoming request by throwing a *temporatily unavailable* exception similar to http status 503. We need to have a timespan and number of exceptions and a wait timespan. We do not dispose at all but ignore.
- to add a delay to prevent certain resources from overloading. Its a sort of throttling.
- kill the whole host without a gracefull termination
- reload the bus instance which can be done if there are no dependencies injected.

Also, IMHO, the circuit breaker must report progress. Not only mention that it is 'armed' but also diagnostics based on current values. For example, report how far of the circuit breaker is of reaching its limit. Not only in raw values but also in a time estimate.

This became a must larger response then I anticipated. If you think this is valuable then I can create another issue and put this info in it.

**Comment by andreasohlund** [comment]
>It has two angles which are hosting and embedding and in both we fail as the behavior is implicit. How many products do you know that really kill them selves?

Needs to be tripple checked but I'm sure that it's only with NSB host that kills it self, ie not when beeing embedded.


>We should be reliable by default and also be reliable for the process in which we are embedded meaning that we need to be a good neighbour. We should not close the door by default as this causes issues for the tasks that depend on us.

Not an issue if my above statement is right?


>A more sensible default would be to have a sort of 'backoff' strategy, delaying execution in combination with recovery. Another strategy is to actually KILL the application by default with an application exit. 

Isn't this exactly what we do? 

https://github.com/Particular/NServiceBus.Host/blob/develop/src/NServiceBus.Hosting.Windows/GenericHost.cs#L168

But I think you're right in the embedded mode, there we just shut the bus down => ie disposes of it


I do agree that we need to provide better config for the circuit breakers, that said most of them are configurable today? (the time to trigger that is)

**Comment by SimonCropp** [comment]
@ramonsmits @andreasohlund so any proposed changes to docs based on this?

**Comment by andreasohlund** [comment]
@ramonsmits do you agree with https://github.com/Particular/docs.particular.net/issues/870#issuecomment-148015624 ?

**Comment by SimonCropp** [comment]
@ramonsmits  please re-open as a PR if ever get back to this
