### ISSUE TITLE
move home page content over to a bootstrap layout

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#914]
to reduce the friction in making modifications to the html

**Comment by SimonCropp** [comment]
@petersgiles @colin-higgins tracking issue for home page changes

**Comment by udidahan** [comment]
is this urgent?

**Comment by SimonCropp** [comment]
@udidahan urgent, no. necessary, yes.

@colin-higgins @petersgiles can one of u give an estimate on the effort?

**Comment by petersgiles** [comment]
It shouldn't cost a lot engineering-wise. We will have to tidy up any inline css but it's already BS3 so there is no difficult migration to consider. 

The only thing is its a little harder to iterate over because of the fragmented way it gets glued together at build time. But @SimonCropp has already suggested a way to make that a little easier. It's a small effort with a medium impact and it fits in with our philosophy of continuous improvement. Optimistically I'd say 1 full day, pessimistically no more than 2-3 days with the odd weird bug on mobile devices and old browsers.

If it turns there are serious design changes required to make it more mobile friendly I think we might have to start a new issue.

**Comment by SimonCropp** [comment]
>  pessimistically no more than 2-3 days with the odd weird bug on mobile devices and old browsers. If it turns there are serious design changes required to make it more mobile friendly I think we might have to start a new issue.

Just to be clear we are not mobile friendly ATM. so  2-3days "making it mobile friendly" would be considered outside the scope of this issue. even though we should do it

**Comment by petersgiles** [comment]
> "making it mobile friendly" would be considered outside the scope of this issue. 

Ok well if we're not testing in that space my answer would be it could be done pretty quick then

**Comment by colin-higgins** [comment]
Yeah, agreed with @petersgiles. Tidying things up would take about a day. We could make a fair bit of progress toward being mobile friendly as well. 

The mobile friendliness could be accomplished with a bunch of incremental changes which would be fairly low effort as well, though as you said it is out of scope.

Low effort / low risk / lowish impact

**Comment by SimonCropp** [comment]
@colin-higgins 

> mobile friendliness could be accomplished with a bunch of incremental changes

yeah that was the conversation pete and I had last week.

**Comment by udidahan** [comment]
OK.

**Comment by petersgiles** [comment]
Is it the page that appears at http://docs.particular.net/ or is it the layout for all the pages that are created by DocsWeb?

**Comment by SimonCropp** [comment]
@petersgiles the contents of this https://github.com/Particular/docs.particular.net/blob/master/home.md

**Comment by SimonCropp** [comment]
> the layout for all the pages that are created by DocsWeb

this will be a next step
