### ISSUE TITLE
Hard to see release notes and downloads on the docs home page

### ISSUE THREAD

**Issue by udidahan** [Particular/docs.particular.net#945]
![image](https://cloud.githubusercontent.com/assets/475886/11402455/af5eb4fe-93a0-11e5-96bb-b965cb733440.png)

ping @sergioc

**Comment by weralabaj** [comment]
@sergioc @udidahan not sure what could be done about that here, does it belong somewhere else? does it need clarification? or maybe has been addressed already?

**Comment by sergioc** [comment]
It belongs here. @udidahan is looking to create better visibility for the Release Notes and Downloads links.

**Comment by udidahan** [comment]
We may need to create an issue in PlatDev to increase its visibility so that it can be prioritized by the squad.

**Comment by weralabaj** [comment]
@Particular/platform-dev-squad would it make sense to open it in PlatformDev repo?

**Comment by adamralph** [comment]
As far as visibility is concerned, it doesn't matter which repo the issue is in, since the board includes all of them. We're currently using the `Consider for Promotion` label to highlight issues which are candidates for next in line work.

The current criteria for an issue existing in PlatDev rather than sub-repo are

* The work spans more than one repo
* The issue is not suitable to be public

**Comment by weralabaj** [comment]
But does the squad actually review and prioritize issues in the docs repo? As fair as I know it's currently done by maintainers, or the docs issue is considered the same priority as a related code change in another repo.
Either way - we can leave it here, if you think it won't get forgotten in the process.

**Comment by SimonCropp** [comment]
font is now slightly bigger and brighter
