### ISSUE TITLE
Guidance on databus and encrypted properties

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#990]
It seems that the recommended practise is to only apply databus and encrypted properties on command messages and not on events.

**Comment by SimonCropp** [comment]
> the recommended practise is to only apply databus and encrypted properties on command messages and not on events

really? why is that?

**Comment by andreasohlund** [comment]
This was me and @ramonsmits talking about how databus properties most likely wouldn't be present on events going across business services

https://skillsmatter.com/skillscasts/2990-events-diet

of course for internal events you could have those type of properties but I would question the use of the databus on those since you want to avoid "moving" large blobs of data around so having it on events would be a bit of a smell IMO.

Does this make any sense at all?

**Comment by SimonCropp** [comment]
It does. But based on that the title is wrong. Also you are getting into a area of "soft recomendations" and not really specific doco for our tooling

**Comment by SimonCropp** [comment]
@andreasohlund @ramonsmits i think this should be a blog post instead
